import { IscedGrade } from '../types/node'
import { localOrg_authId } from './content'

// @ts-ignore: this is a static initial population array, no need to ts check
const _: IscedGrade[] = [
  {
    _permId: 'ED01',
    _type: 'IscedGrade',
    _slug: 'ed01-early-childhood-educational-development',
    _published: false,
    name: 'Early childhood educational development',
    codePath: ['0', '1'],
    code: 'ED01',
    description: 'Early childhood educational development',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED0',
    _type: 'IscedGrade',
    _slug: 'ed0-early-childhood-education',
    _published: true,
    name: 'Early childhood education',
    codePath: ['0'],
    code: 'ED0',
    description: 'Early childhood education',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED02',
    _type: 'IscedGrade',
    _slug: 'ed02-pre-primary-education',
    _published: false,
    name: 'Pre-primary education',
    codePath: ['0', '2'],
    code: 'ED02',
    description: 'Pre-primary education',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED1',
    _type: 'IscedGrade',
    _slug: 'ed1-primary-education',
    _published: true,
    name: 'Primary education',
    codePath: ['1'],
    code: 'ED1',
    description: 'Primary education',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED2',
    _type: 'IscedGrade',
    _slug: 'ed2-lower-secondary-education',
    _published: true,
    name: 'Lower secondary education',
    codePath: ['2'],
    code: 'ED2',
    description: 'Lower secondary education',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED24',
    _type: 'IscedGrade',
    _slug: 'ed24-lower-secondary-education-general',
    _published: false,
    name: 'Lower secondary education - general',
    codePath: ['2', '4'],
    code: 'ED24',
    description: 'Lower secondary education - general',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED25',
    _type: 'IscedGrade',
    _slug: 'ed25-lower-secondary-education-vocational',
    _published: false,
    name: 'Lower secondary education - vocational',
    codePath: ['2', '5'],
    code: 'ED25',
    description: 'Lower secondary education - vocational',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED3',
    _type: 'IscedGrade',
    _slug: 'ed3-upper-secondary-education',
    _published: true,
    name: 'Upper secondary education',
    codePath: ['3'],
    code: 'ED3',
    description: 'Upper secondary education',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED34',
    _type: 'IscedGrade',
    _slug: 'ed34-upper-secondary-education-general',
    _published: false,
    name: 'Upper secondary education - general',
    codePath: ['3', '4'],
    code: 'ED34',
    description: 'Upper secondary education - general',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED341',
    _type: 'IscedGrade',
    _slug:
      'ed341-upper-secondary-education-general-insufficient-for-level-completion-or-partial-level-completion-without-direct-access-to-tertiary-education',
    _published: false,
    name: 'Upper secondary education - general, insufficient for level completion or partial level completion, without direct access to tertiary education',
    codePath: ['3', '4', '1'],
    code: 'ED341',
    description:
      'Upper secondary education - general, insufficient for level completion or partial level completion, without direct access to tertiary education',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED342',
    _type: 'IscedGrade',
    _slug:
      'ed342-upper-secondary-education-general-sufficient-for-partial-level-completion-without-direct-access-to-tertiary-education',
    _published: false,
    name: 'Upper secondary education - general, sufficient for partial level completion, without direct access to tertiary education',
    codePath: ['3', '4', '2'],
    code: 'ED342',
    description:
      'Upper secondary education - general, sufficient for partial level completion, without direct access to tertiary education',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED343',
    _type: 'IscedGrade',
    _slug:
      'ed343-upper-secondary-education-general-sufficient-for-level-completion-without-direct-access-to-tertiary-education',
    _published: false,
    name: 'Upper secondary education - general, sufficient for level completion, without direct access to tertiary education',
    codePath: ['3', '4', '3'],
    code: 'ED343',
    description:
      'Upper secondary education - general, sufficient for level completion, without direct access to tertiary education',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED344',
    _type: 'IscedGrade',
    _slug:
      'ed344-upper-secondary-education-general-sufficient-for-level-completion-with-direct-access-to-tertiary-education',
    _published: false,
    name: 'Upper secondary education - general, sufficient for level completion, with direct access to tertiary education',
    codePath: ['3', '4', '4'],
    code: 'ED344',
    description:
      'Upper secondary education - general, sufficient for level completion, with direct access to tertiary education',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED35',
    _type: 'IscedGrade',
    _slug: 'ed35-upper-secondary-education-vocational',
    _published: false,
    name: 'Upper secondary education - vocational',
    codePath: ['3', '5'],
    code: 'ED35',
    description: 'Upper secondary education - vocational',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED351',
    _type: 'IscedGrade',
    _slug:
      'ed351-upper-secondary-education-vocational-insufficient-for-level-completion-or-partial-level-completion-without-direct-access-to-tertiary-education',
    _published: false,
    name: 'Upper secondary education - vocational, insufficient for level completion or partial level completion, without direct access to tertiary education',
    codePath: ['3', '5', '1'],
    code: 'ED351',
    description:
      'Upper secondary education - vocational, insufficient for level completion or partial level completion, without direct access to tertiary education',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED352',
    _type: 'IscedGrade',
    _slug:
      'ed352-upper-secondary-education-vocational-sufficient-for-partial-level-completion-without-direct-access-to-tertiary-education',
    _published: false,
    name: 'Upper secondary education - vocational, sufficient for partial level completion, without direct access to tertiary education',
    codePath: ['3', '5', '2'],
    code: 'ED352',
    description:
      'Upper secondary education - vocational, sufficient for partial level completion, without direct access to tertiary education',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED353',
    _type: 'IscedGrade',
    _slug:
      'ed353-upper-secondary-education-vocational-sufficient-for-level-completion-without-direct-access-to-tertiary-education',
    _published: false,
    name: 'Upper secondary education - vocational, sufficient for level completion, without direct access to tertiary education',
    codePath: ['3', '5', '3'],
    code: 'ED353',
    description:
      'Upper secondary education - vocational, sufficient for level completion, without direct access to tertiary education',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED354',
    _type: 'IscedGrade',
    _slug:
      'ed354-upper-secondary-education-vocational-sufficient-for-level-completion-with-direct-access-to-tertiary-education',
    _published: false,
    name: 'Upper secondary education - vocational, sufficient for level completion, with direct access to tertiary education',
    codePath: ['3', '5', '4'],
    code: 'ED354',
    description:
      'Upper secondary education - vocational, sufficient for level completion, with direct access to tertiary education',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED4',
    _type: 'IscedGrade',
    _slug: 'ed4-post-secondary-non-tertiary-education',
    _published: true,
    name: 'Post-secondary non-tertiary education',
    codePath: ['4'],
    code: 'ED4',
    description: 'Post-secondary non-tertiary education',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED44',
    _type: 'IscedGrade',
    _slug: 'ed44-post-secondary-non-tertiary-education-general',
    _published: false,
    name: 'Post-secondary non-tertiary education - general',
    codePath: ['4', '4'],
    code: 'ED44',
    description: 'Post-secondary non-tertiary education - general',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED441',
    _type: 'IscedGrade',
    _slug:
      'ed441-post-secondary-non-tertiary-education-general-insufficient-for-level-completion-without-direct-access-to-tertiary-education',
    _published: false,
    name: 'Post-secondary non-tertiary education - general, insufficient for level completion, without direct access to tertiary education',
    codePath: ['4', '4', '1'],
    code: 'ED441',
    description:
      'Post-secondary non-tertiary education - general, insufficient for level completion, without direct access to tertiary education',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED443',
    _type: 'IscedGrade',
    _slug:
      'ed443-post-secondary-non-tertiary-education-general-sufficient-for-level-completion-without-direct-access-to-tertiary-education',
    _published: false,
    name: 'Post-secondary non-tertiary education - general, sufficient for level completion, without direct access to tertiary education',
    codePath: ['4', '4', '3'],
    code: 'ED443',
    description:
      'Post-secondary non-tertiary education - general, sufficient for level completion, without direct access to tertiary education',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED444',
    _type: 'IscedGrade',
    _slug:
      'ed444-post-secondary-non-tertiary-education-general-sufficient-for-level-completion-with-direct-access-to-tertiary-education',
    _published: false,
    name: 'Post-secondary non-tertiary education - general, sufficient for level completion, with direct access to tertiary education',
    codePath: ['4', '4', '4'],
    code: 'ED444',
    description:
      'Post-secondary non-tertiary education - general, sufficient for level completion, with direct access to tertiary education',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED45',
    _type: 'IscedGrade',
    _slug: 'ed45-post-secondary-non-tertiary-education-vocational',
    _published: false,
    name: 'Post-secondary non-tertiary education - vocational',
    codePath: ['4', '5'],
    code: 'ED45',
    description: 'Post-secondary non-tertiary education - vocational',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED451',
    _type: 'IscedGrade',
    _slug:
      'ed451-post-secondary-non-tertiary-education-vocational-insufficient-for-level-completion-without-direct-access-to-tertiary-education',
    _published: false,
    name: 'Post-secondary non-tertiary education - vocational, insufficient for level completion, without direct access to tertiary education',
    codePath: ['4', '5', '1'],
    code: 'ED451',
    description:
      'Post-secondary non-tertiary education - vocational, insufficient for level completion, without direct access to tertiary education',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED453',
    _type: 'IscedGrade',
    _slug:
      'ed453-post-secondary-non-tertiary-education-vocational-sufficient-for-level-completion-without-direct-access-to-tertiary-education',
    _published: false,
    name: 'Post-secondary non-tertiary education - vocational, sufficient for level completion, without direct access to tertiary education',
    codePath: ['4', '5', '3'],
    code: 'ED453',
    description:
      'Post-secondary non-tertiary education - vocational, sufficient for level completion, without direct access to tertiary education',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED454',
    _type: 'IscedGrade',
    _slug:
      'ed454-post-secondary-non-tertiary-education-vocational-sufficient-for-level-completion-with-direct-access-to-tertiary-education',
    _published: false,
    name: 'Post-secondary non-tertiary education - vocational, sufficient for level completion, with direct access to tertiary education',
    codePath: ['4', '5', '4'],
    code: 'ED454',
    description:
      'Post-secondary non-tertiary education - vocational, sufficient for level completion, with direct access to tertiary education',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED5',
    _type: 'IscedGrade',
    _slug: 'ed5-tertiary-education',
    _published: true,
    name: 'Tertiary education',
    codePath: ['5'],
    code: 'ED5',
    description: 'Tertiary education',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED54',
    _type: 'IscedGrade',
    _slug: 'ed54-tertiary-education-general-academic',
    _published: false,
    name: 'Tertiary education - general/academic',
    codePath: ['5', '4'],
    code: 'ED54',
    description: 'Tertiary education - general/academic',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED541',
    _type: 'IscedGrade',
    _slug: 'ed541-tertiary-education-general-academic-insufficient-for-level-completion',
    _published: false,
    name: 'Tertiary education - general/academic, insufficient for level completion',
    codePath: ['5', '4', '1'],
    code: 'ED541',
    description: 'Tertiary education - general/academic, insufficient for level completion',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED544',
    _type: 'IscedGrade',
    _slug: 'ed544-tertiary-education-general-academic-sufficient-for-level-completion',
    _published: false,
    name: 'Tertiary education - general/academic, sufficient for level completion',
    codePath: ['5', '4', '4'],
    code: 'ED544',
    description: 'Tertiary education - general/academic, sufficient for level completion',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED55',
    _type: 'IscedGrade',
    _slug: 'ed55-tertiary-education-vocational-professional',
    _published: false,
    name: 'Tertiary education - vocational/professional',
    codePath: ['5', '5'],
    code: 'ED55',
    description: 'Tertiary education - vocational/professional',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED551',
    _type: 'IscedGrade',
    _slug: 'ed551-tertiary-education-vocational-professional-insufficient-for-level-completion',
    _published: false,
    name: 'Tertiary education - vocational/professional, insufficient for level completion',
    codePath: ['5', '5', '1'],
    code: 'ED551',
    description: 'Tertiary education - vocational/professional, insufficient for level completion',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED554',
    _type: 'IscedGrade',
    _slug: 'ed554-tertiary-education-vocational-professional-sufficient-for-level-completion',
    _published: false,
    name: 'Tertiary education - vocational/professional, sufficient for level completion',
    codePath: ['5', '5', '4'],
    code: 'ED554',
    description: 'Tertiary education - vocational/professional, sufficient for level completion',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED6',
    _type: 'IscedGrade',
    _slug: 'ed6-bachelors-or-equivalent',
    _published: true,
    name: 'Bachelor’s or equivalent',
    codePath: ['6'],
    code: 'ED6',
    description: 'Bachelor’s or equivalent',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED64',
    _type: 'IscedGrade',
    _slug: 'ed64-bachelors-or-equivalent-academic',
    _published: false,
    name: "Bachelor's or equivalent - academic",
    codePath: ['6', '4'],
    code: 'ED64',
    description: "Bachelor's or equivalent - academic",
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED641',
    _type: 'IscedGrade',
    _slug: 'ed641-bachelors-or-equivalent-academic-insufficient-for-level-completion',
    _published: false,
    name: "Bachelor's or equivalent - academic, insufficient for level completion",
    codePath: ['6', '4', '1'],
    code: 'ED641',
    description: "Bachelor's or equivalent - academic, insufficient for level completion",
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED645',
    _type: 'IscedGrade',
    _slug: 'ed645-bachelors-or-equivalent-academic-first-degree-3-4-years',
    _published: false,
    name: "Bachelor's or equivalent - academic, first degree (3-4 years)",
    codePath: ['6', '4', '5'],
    code: 'ED645',
    description: "Bachelor's or equivalent - academic, first degree (3-4 years)",
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED646',
    _type: 'IscedGrade',
    _slug: 'ed646-bachelors-or-equivalent-academic-long-first-degree-more-than-4-years',
    _published: false,
    name: "Bachelor's or equivalent - academic, long first degree (more than 4 years)",
    codePath: ['6', '4', '6'],
    code: 'ED646',
    description: "Bachelor's or equivalent - academic, long first degree (more than 4 years)",
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED647',
    _type: 'IscedGrade',
    _slug:
      'ed647-bachelors-or-equivalent-academic-second-or-further-degree-following-a-bachelors-or-equivalent-programme',
    _published: false,
    name: "Bachelor's or equivalent - academic, second or further degree (following a Bachelor's or equivalent programme)",
    codePath: ['6', '4', '7'],
    code: 'ED647',
    description:
      "Bachelor's or equivalent - academic, second or further degree (following a Bachelor's or equivalent programme)",
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED65',
    _type: 'IscedGrade',
    _slug: 'ed65-bachelors-or-equivalent-professional',
    _published: false,
    name: "Bachelor's or equivalent - professional",
    codePath: ['6', '5'],
    code: 'ED65',
    description: "Bachelor's or equivalent - professional",
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED655',
    _type: 'IscedGrade',
    _slug: 'ed655-bachelors-or-equivalent-professional-first-degree-3-4-years',
    _published: false,
    name: "Bachelor's or equivalent - professional, first degree (3-4 years)",
    codePath: ['6', '5', '5'],
    code: 'ED655',
    description: "Bachelor's or equivalent - professional, first degree (3-4 years)",
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED651',
    _type: 'IscedGrade',
    _slug: 'ed651-bachelors-or-equivalent-professional-insufficient-for-level-completion',
    _published: false,
    name: "Bachelor's or equivalent - professional, insufficient for level completion",
    codePath: ['6', '5', '1'],
    code: 'ED651',
    description: "Bachelor's or equivalent - professional, insufficient for level completion",
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED656',
    _type: 'IscedGrade',
    _slug: 'ed656-bachelors-or-equivalent-professional-long-first-degree-more-than-4-years',
    _published: false,
    name: "Bachelor's or equivalent - professional, long first degree (more than 4 years)",
    codePath: ['6', '5', '6'],
    code: 'ED656',
    description: "Bachelor's or equivalent - professional, long first degree (more than 4 years)",
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED657',
    _type: 'IscedGrade',
    _slug:
      'ed657-bachelors-or-equivalent-professional-second-or-further-degree-following-a-bachelors-or-equivalent-programme',
    _published: false,
    name: "Bachelor's or equivalent - professional, second or further degree (following a Bachelor's or equivalent programme)",
    codePath: ['6', '5', '7'],
    code: 'ED657',
    description:
      "Bachelor's or equivalent - professional, second or further degree (following a Bachelor's or equivalent programme)",
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED66',
    _type: 'IscedGrade',
    _slug: 'ed66-bachelors-or-equivalent-orientation-unspecified',
    _published: false,
    name: "Bachelor's or equivalent - orientation unspecified",
    codePath: ['6', '6'],
    code: 'ED66',
    description: "Bachelor's or equivalent - orientation unspecified",
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED661',
    _type: 'IscedGrade',
    _slug: 'ed661-bachelors-or-equivalent-orientation-unspecified-insufficient-for-level-completion',
    _published: false,
    name: "Bachelor's or equivalent - orientation unspecified, insufficient for level completion",
    codePath: ['6', '6', '1'],
    code: 'ED661',
    description: "Bachelor's or equivalent - orientation unspecified, insufficient for level completion",
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED665',
    _type: 'IscedGrade',
    _slug: 'ed665-bachelors-or-equivalent-orientation-unspecified-first-degree-3-4-years',
    _published: false,
    name: "Bachelor's or equivalent - orientation unspecified, first degree (3-4 years)",
    codePath: ['6', '6', '5'],
    code: 'ED665',
    description: "Bachelor's or equivalent - orientation unspecified, first degree (3-4 years)",
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED666',
    _type: 'IscedGrade',
    _slug: 'ed666-bachelors-or-equivalent-orientation-unspecified-long-first-degree-more-than-4-years',
    _published: false,
    name: "Bachelor's or equivalent - orientation unspecified, long first degree (more than 4 years)",
    codePath: ['6', '6', '6'],
    code: 'ED666',
    description: "Bachelor's or equivalent - orientation unspecified, long first degree (more than 4 years)",
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED667',
    _type: 'IscedGrade',
    _slug:
      'ed667-bachelors-or-equivalent-orientation-unspecified-second-or-further-degree-following-a-bachelors-or-equivalent-programme',
    _published: false,
    name: "Bachelor's or equivalent - orientation unspecified, second or further degree (following a Bachelor's or equivalent programme)",
    codePath: ['6', '6', '7'],
    code: 'ED667',
    description:
      "Bachelor's or equivalent - orientation unspecified, second or further degree (following a Bachelor's or equivalent programme)",
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED7',
    _type: 'IscedGrade',
    _slug: 'ed7-masters-or-equivalent',
    _published: true,
    name: 'Master’s or equivalent',
    codePath: ['7'],
    code: 'ED7',
    description: 'Master’s or equivalent',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED74',
    _type: 'IscedGrade',
    _slug: 'ed74-masters-or-equivalent-academic',
    _published: false,
    name: "Master's or equivalent - academic",
    codePath: ['7', '4'],
    code: 'ED74',
    description: "Master's or equivalent - academic",
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED741',
    _type: 'IscedGrade',
    _slug: 'ed741-masters-or-equivalent-academic-insufficient-for-level-completion',
    _published: false,
    name: "Master's or equivalent - academic, insufficient for level completion",
    codePath: ['7', '4', '1'],
    code: 'ED741',
    description: "Master's or equivalent - academic, insufficient for level completion",
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED746',
    _type: 'IscedGrade',
    _slug: 'ed746-masters-or-equivalent-academic-long-first-degree-at-least-5-years',
    _published: false,
    name: "Master's or equivalent - academic, long first degree (at least 5 years)",
    codePath: ['7', '4', '6'],
    code: 'ED746',
    description: "Master's or equivalent - academic, long first degree (at least 5 years)",
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED748',
    _type: 'IscedGrade',
    _slug: 'ed748-masters-or-equivalent-academic-second-or-further-degree-following-a-masters-or-equivalent-programme',
    _published: false,
    name: "Master's or equivalent - academic, second or further degree (following a Master's or equivalent programme)",
    codePath: ['7', '4', '8'],
    code: 'ED748',
    description:
      "Master's or equivalent - academic, second or further degree (following a Master's or equivalent programme)",
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED747',
    _type: 'IscedGrade',
    _slug:
      'ed747-masters-or-equivalent-academic-second-or-further-degree-following-a-bachelors-or-equivalent-programme',
    _published: false,
    name: "Master's or equivalent - academic, second or further degree (following a Bachelor's or equivalent programme)",
    codePath: ['7', '4', '7'],
    code: 'ED747',
    description:
      "Master's or equivalent - academic, second or further degree (following a Bachelor's or equivalent programme)",
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED75',
    _type: 'IscedGrade',
    _slug: 'ed75-masters-or-equivalent-professional',
    _published: false,
    name: "Master's or equivalent - professional",
    codePath: ['7', '5'],
    code: 'ED75',
    description: "Master's or equivalent - professional",
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED751',
    _type: 'IscedGrade',
    _slug: 'ed751-masters-or-equivalent-professional-insufficient-for-level-completion',
    _published: false,
    name: "Master's or equivalent - professional, insufficient for level completion",
    codePath: ['7', '5', '1'],
    code: 'ED751',
    description: "Master's or equivalent - professional, insufficient for level completion",
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED756',
    _type: 'IscedGrade',
    _slug: 'ed756-masters-or-equivalent-professional-long-first-degree-at-least-5-years',
    _published: false,
    name: "Master's or equivalent - professional, long first degree (at least 5 years)",
    codePath: ['7', '5', '6'],
    code: 'ED756',
    description: "Master's or equivalent - professional, long first degree (at least 5 years)",
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED757',
    _type: 'IscedGrade',
    _slug:
      'ed757-masters-or-equivalent-professional-second-or-further-degree-following-a-bachelors-or-equivalent-programme',
    _published: false,
    name: "Master's or equivalent - professional, second or further degree (following a Bachelor's or equivalent programme)",
    codePath: ['7', '5', '7'],
    code: 'ED757',
    description:
      "Master's or equivalent - professional, second or further degree (following a Bachelor's or equivalent programme)",
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED758',
    _type: 'IscedGrade',
    _slug:
      'ed758-masters-or-equivalent-professional-second-or-further-degree-following-a-masters-or-equivalent-programme',
    _published: false,
    name: "Master's or equivalent - professional, second or further degree (following a Master's or equivalent programme)",
    codePath: ['7', '5', '8'],
    code: 'ED758',
    description:
      "Master's or equivalent - professional, second or further degree (following a Master's or equivalent programme)",
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED76',
    _type: 'IscedGrade',
    _slug: 'ed76-masters-or-equivalent-orientation-unspecified',
    _published: false,
    name: "Master's or equivalent - orientation unspecified",
    codePath: ['7', '6'],
    code: 'ED76',
    description: "Master's or equivalent - orientation unspecified",
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED761',
    _type: 'IscedGrade',
    _slug: 'ed761-masters-or-equivalent-orientation-unspecified-insufficient-for-level-completion',
    _published: false,
    name: "Master's or equivalent - orientation unspecified, insufficient for level completion",
    codePath: ['7', '6', '1'],
    code: 'ED761',
    description: "Master's or equivalent - orientation unspecified, insufficient for level completion",
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED766',
    _type: 'IscedGrade',
    _slug: 'ed766-masters-or-equivalent-orientation-unspecified-long-first-degree-at-least-5-years',
    _published: false,
    name: "Master's or equivalent - orientation unspecified, long first degree (at least 5 years)",
    codePath: ['7', '6', '6'],
    code: 'ED766',
    description: "Master's or equivalent - orientation unspecified, long first degree (at least 5 years)",
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED767',
    _type: 'IscedGrade',
    _slug:
      'ed767-masters-or-equivalent-orientation-unspecified-second-or-further-degree-following-a-bachelors-or-equivalent-programme',
    _published: false,
    name: "Master's or equivalent - orientation unspecified, second or further degree (following a Bachelor's or equivalent programme)",
    codePath: ['7', '6', '7'],
    code: 'ED767',
    description:
      "Master's or equivalent - orientation unspecified, second or further degree (following a Bachelor's or equivalent programme)",
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED768',
    _type: 'IscedGrade',
    _slug:
      'ed768-masters-or-equivalent-orientation-unspecified-second-or-further-degree-following-a-masters-or-equivalent-programme',
    _published: false,
    name: "Master's or equivalent - orientation unspecified, second or further degree (following a Master's or equivalent programme)",
    codePath: ['7', '6', '8'],
    code: 'ED768',
    description:
      "Master's or equivalent - orientation unspecified, second or further degree (following a Master's or equivalent programme)",
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ED8',
    _type: 'IscedGrade',
    _slug: 'ed8-doctoral-or-equivalent',
    _published: true,
    name: 'Doctoral or equivalent',
    codePath: ['8'],
    code: 'ED8',
    description: 'Doctoral or equivalent',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'ADT',
    _type: 'IscedGrade',
    _slug: 'adt-adult-education',
    _published: true,
    name: 'Adult Education',
    codePath: ['ADT'],
    code: 'ADT',
    description: 'Adult Education',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
]
export default _
