export const INVALID_TOKEN = 'INVALID_TOKEN'
export const INVALID_TOKEN_AUD = 'INVALID_TOKEN_AUD'
export const INVALID_TOKEN_TYPE = 'INVALID_TOKEN_TYPE'
export type TYPE_INVALID_TOKEN = typeof INVALID_TOKEN | typeof INVALID_TOKEN_AUD | typeof INVALID_TOKEN_TYPE
