export const resTypeMap: Record<string, string> = {
  'assessment': 'assessment',
  'graph': 'graph',
  'experiment': 'experiment',
  'figure': 'graph',
  'game': 'game',
  'guides': 'guides-and-tutorials',
  'index': 'glossary',
  'lecture': 'guides-and-tutorials',
  'map': 'map',
  'narrative-text': 'reading',
  'problem-statement': 'assessment',
  'questionnaire': 'questionnaire',
  'references': 'references',
  'reports': 'report',
  'simulation': 'simulation',
  'slide': 'reading',
  'table': 'data-set',
}
