export const GOOGLE_CLIENT_ID = '760051383014-iln3njej3ij9otp0jufrkvo1lu40i6k4.apps.googleusercontent.com'
export const GOOGLE_CLIENT_SECRET = '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'
export const SERVER_ROOT_URI = 'http://localhost:4000'
export const UI_ROOT_URI = 'http://localhost:3001'
export const JWT_SECRET = 'shhhhh'
export const COOKIE_NAME = 'auth_token'
