import { IscedField } from '../types/node'
import { localOrg_authId } from './content'

// @ts-ignore: this is a static initial population array, no need to ts check
const _: IscedField[] = [
  {
    _permId: 'F00',
    _type: 'IscedField',
    _slug: 'f00-generic-programmes-and-qualifications',
    _published: true,
    name: 'Generic programmes and qualifications',
    codePath: ['F00'],
    code: 'F00',
    description: 'Generic programmes and qualifications',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F000',
    _type: 'IscedField',
    _slug: 'f000-generic-programmes-and-qualifications-not-further-defined',
    _published: false,
    name: 'Generic programmes and qualifications not further defined',
    codePath: ['F00', '0'],
    code: 'F000',
    description: 'Generic programmes and qualifications not further defined',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0000',
    _type: 'IscedField',
    _slug: 'f0000-generic-programmes-and-qualifications-not-further-defined',
    _published: false,
    name: 'Generic programmes and qualifications not further defined',
    codePath: ['F00', '0', '0'],
    code: 'F0000',
    description: 'Generic programmes and qualifications not further defined',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F001',
    _type: 'IscedField',
    _slug: 'f001-basic-programmes-and-qualifications',
    _published: true,
    name: 'Basic programmes and qualifications',
    codePath: ['F00', '1'],
    code: 'F001',
    description: 'Basic programmes and qualifications',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0011',
    _type: 'IscedField',
    _slug: 'f0011-basic-programmes-and-qualifications',
    _published: false,
    name: 'Basic programmes and qualifications',
    codePath: ['F00', '1', '1'],
    code: 'F0011',
    description: 'Basic programmes and qualifications',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F002',
    _type: 'IscedField',
    _slug: 'f002-literacy-and-numeracy',
    _published: true,
    name: 'Literacy and numeracy',
    codePath: ['F00', '2'],
    code: 'F002',
    description: 'Literacy and numeracy',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0021',
    _type: 'IscedField',
    _slug: 'f0021-literacy-and-numeracy',
    _published: false,
    name: 'Literacy and numeracy',
    codePath: ['F00', '2', '1'],
    code: 'F0021',
    description: 'Literacy and numeracy',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F003',
    _type: 'IscedField',
    _slug: 'f003-personal-skills-and-development',
    _published: true,
    name: 'Personal skills and development',
    codePath: ['F00', '3'],
    code: 'F003',
    description: 'Personal skills and development',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0031',
    _type: 'IscedField',
    _slug: 'f0031-personal-skills-and-development',
    _published: false,
    name: 'Personal skills and development',
    codePath: ['F00', '3', '1'],
    code: 'F0031',
    description: 'Personal skills and development',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F009',
    _type: 'IscedField',
    _slug: 'f009-generic-programmes-and-qualifications-not-elsewhere-classified',
    _published: false,
    name: 'Generic programmes and qualifications not elsewhere classified',
    codePath: ['F00', '9'],
    code: 'F009',
    description: 'Generic programmes and qualifications not elsewhere classified',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0099',
    _type: 'IscedField',
    _slug: 'f0099-generic-programmes-and-qualifications-not-elsewhere-classified',
    _published: false,
    name: 'Generic programmes and qualifications not elsewhere classified',
    codePath: ['F00', '9', '9'],
    code: 'F0099',
    description: 'Generic programmes and qualifications not elsewhere classified',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F01',
    _type: 'IscedField',
    _slug: 'f01-education',
    _published: true,
    name: 'Education',
    codePath: ['F01'],
    code: 'F01',
    description: 'Education',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F011',
    _type: 'IscedField',
    _slug: 'f011-education',
    _published: false,
    name: 'Education',
    codePath: ['F01', '1'],
    code: 'F011',
    description: 'Education',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0110',
    _type: 'IscedField',
    _slug: 'f0110-education-not-further-defined',
    _published: false,
    name: 'Education not further defined',
    codePath: ['F01', '1', '0'],
    code: 'F0110',
    description: 'Education not further defined',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0111',
    _type: 'IscedField',
    _slug: 'f0111-education-science',
    _published: true,
    name: 'Education science',
    codePath: ['F01', '1', '1'],
    code: 'F0111',
    description: 'Education science',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0112',
    _type: 'IscedField',
    _slug: 'f0112-training-for-pre-school-teachers',
    _published: true,
    name: 'Training for pre-school teachers',
    codePath: ['F01', '1', '2'],
    code: 'F0112',
    description: 'Training for pre-school teachers',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0113',
    _type: 'IscedField',
    _slug: 'f0113-teacher-training-without-subject-specialisation',
    _published: true,
    name: 'Teacher training without subject specialisation',
    codePath: ['F01', '1', '3'],
    code: 'F0113',
    description: 'Teacher training without subject specialisation',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0114',
    _type: 'IscedField',
    _slug: 'f0114-teacher-training-with-subject-specialisation',
    _published: true,
    name: 'Teacher training with subject specialisation',
    codePath: ['F01', '1', '4'],
    code: 'F0114',
    description: 'Teacher training with subject specialisation',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0119',
    _type: 'IscedField',
    _slug: 'f0119-education-not-elsewhere-classified',
    _published: false,
    name: 'Education not elsewhere classified',
    codePath: ['F01', '1', '9'],
    code: 'F0119',
    description: 'Education not elsewhere classified',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F018',
    _type: 'IscedField',
    _slug: 'f018-inter-disciplinary-programmes-and-qualifications-involving-education',
    _published: true,
    name: 'Inter-disciplinary programmes and qualifications involving education',
    codePath: ['F01', '8'],
    code: 'F018',
    description: 'Inter-disciplinary programmes and qualifications involving education',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0188',
    _type: 'IscedField',
    _slug: 'f0188-inter-disciplinary-programmes-and-qualifications-involving-education',
    _published: false,
    name: 'Inter-disciplinary programmes and qualifications involving education',
    codePath: ['F01', '8', '8'],
    code: 'F0188',
    description: 'Inter-disciplinary programmes and qualifications involving education',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F02',
    _type: 'IscedField',
    _slug: 'f02-arts-and-humanities',
    _published: true,
    name: 'Arts and humanities',
    codePath: ['F02'],
    code: 'F02',
    description: 'Arts and humanities',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F020',
    _type: 'IscedField',
    _slug: 'f020-arts-and-humanities-not-further-defined',
    _published: false,
    name: 'Arts and humanities not further defined',
    codePath: ['F02', '0'],
    code: 'F020',
    description: 'Arts and humanities not further defined',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0200',
    _type: 'IscedField',
    _slug: 'f0200-arts-and-humanities-not-further-defined',
    _published: false,
    name: 'Arts and humanities not further defined',
    codePath: ['F02', '0', '0'],
    code: 'F0200',
    description: 'Arts and humanities not further defined',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F021',
    _type: 'IscedField',
    _slug: 'f021-arts',
    _published: true,
    name: 'Arts',
    codePath: ['F02', '1'],
    code: 'F021',
    description: 'Arts',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0210',
    _type: 'IscedField',
    _slug: 'f0210-arts-not-further-defined',
    _published: false,
    name: 'Arts not further defined',
    codePath: ['F02', '1', '0'],
    code: 'F0210',
    description: 'Arts not further defined',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0211',
    _type: 'IscedField',
    _slug: 'f0211-audio-visual-techniques-and-media-production',
    _published: true,
    name: 'Audio-visual techniques and media production',
    codePath: ['F02', '1', '1'],
    code: 'F0211',
    description: 'Audio-visual techniques and media production',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0212',
    _type: 'IscedField',
    _slug: 'f0212-fashion-interior-and-industrial-design',
    _published: true,
    name: 'Fashion, interior and industrial design',
    codePath: ['F02', '1', '2'],
    code: 'F0212',
    description: 'Fashion, interior and industrial design',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0213',
    _type: 'IscedField',
    _slug: 'f0213-fine-arts',
    _published: true,
    name: 'Fine arts',
    codePath: ['F02', '1', '3'],
    code: 'F0213',
    description: 'Fine arts',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0214',
    _type: 'IscedField',
    _slug: 'f0214-handicrafts',
    _published: true,
    name: 'Handicrafts',
    codePath: ['F02', '1', '4'],
    code: 'F0214',
    description: 'Handicrafts',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0215',
    _type: 'IscedField',
    _slug: 'f0215-music-and-performing-arts',
    _published: true,
    name: 'Music and performing arts',
    codePath: ['F02', '1', '5'],
    code: 'F0215',
    description: 'Music and performing arts',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0219',
    _type: 'IscedField',
    _slug: 'f0219-arts-not-elsewhere-classified',
    _published: false,
    name: 'Arts not elsewhere classified',
    codePath: ['F02', '1', '9'],
    code: 'F0219',
    description: 'Arts not elsewhere classified',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F022',
    _type: 'IscedField',
    _slug: 'f022-humanities-except-languages',
    _published: true,
    name: 'Humanities (except languages)',
    codePath: ['F02', '2'],
    code: 'F022',
    description: 'Humanities (except languages)',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0220',
    _type: 'IscedField',
    _slug: 'f0220-humanities-except-languages-not-further-defined',
    _published: false,
    name: 'Humanities (except languages) not further defined',
    codePath: ['F02', '2', '0'],
    code: 'F0220',
    description: 'Humanities (except languages) not further defined',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0221',
    _type: 'IscedField',
    _slug: 'f0221-religion-and-theology',
    _published: true,
    name: 'Religion and theology',
    codePath: ['F02', '2', '1'],
    code: 'F0221',
    description: 'Religion and theology',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0222',
    _type: 'IscedField',
    _slug: 'f0222-history-and-archaeology',
    _published: true,
    name: 'History and archaeology',
    codePath: ['F02', '2', '2'],
    code: 'F0222',
    description: 'History and archaeology',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0223',
    _type: 'IscedField',
    _slug: 'f0223-philosophy-and-ethics',
    _published: true,
    name: 'Philosophy and ethics',
    codePath: ['F02', '2', '3'],
    code: 'F0223',
    description: 'Philosophy and ethics',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0229',
    _type: 'IscedField',
    _slug: 'f0229-humanities-except-languages-not-elsewhere-classified',
    _published: false,
    name: 'Humanities (except languages) not elsewhere classified',
    codePath: ['F02', '2', '9'],
    code: 'F0229',
    description: 'Humanities (except languages) not elsewhere classified',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F023',
    _type: 'IscedField',
    _slug: 'f023-languages',
    _published: true,
    name: 'Languages',
    codePath: ['F02', '3'],
    code: 'F023',
    description: 'Languages',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0230',
    _type: 'IscedField',
    _slug: 'f0230-languages-not-further-defined',
    _published: false,
    name: 'Languages not further defined',
    codePath: ['F02', '3', '0'],
    code: 'F0230',
    description: 'Languages not further defined',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0231',
    _type: 'IscedField',
    _slug: 'f0231-language-acquisition',
    _published: true,
    name: 'Language acquisition',
    codePath: ['F02', '3', '1'],
    code: 'F0231',
    description: 'Language acquisition',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0232',
    _type: 'IscedField',
    _slug: 'f0232-literature-and-linguistics',
    _published: true,
    name: 'Literature and linguistics',
    codePath: ['F02', '3', '2'],
    code: 'F0232',
    description: 'Literature and linguistics',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0239',
    _type: 'IscedField',
    _slug: 'f0239-languages-not-elsewhere-classified',
    _published: false,
    name: 'Languages not elsewhere classified',
    codePath: ['F02', '3', '9'],
    code: 'F0239',
    description: 'Languages not elsewhere classified',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F028',
    _type: 'IscedField',
    _slug: 'f028-inter-disciplinary-programmes-and-qualifications-involving-arts-and-humanities',
    _published: true,
    name: 'Inter-disciplinary programmes and qualifications involving arts and humanities',
    codePath: ['F02', '8'],
    code: 'F028',
    description: 'Inter-disciplinary programmes and qualifications involving arts and humanities',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0288',
    _type: 'IscedField',
    _slug: 'f0288-inter-disciplinary-programmes-and-qualifications-involving-arts-and-humanities',
    _published: false,
    name: 'Inter-disciplinary programmes and qualifications involving arts and humanities',
    codePath: ['F02', '8', '8'],
    code: 'F0288',
    description: 'Inter-disciplinary programmes and qualifications involving arts and humanities',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F029',
    _type: 'IscedField',
    _slug: 'f029-arts-and-humanities-not-elsewhere-classified',
    _published: false,
    name: 'Arts and humanities not elsewhere classified',
    codePath: ['F02', '9'],
    code: 'F029',
    description: 'Arts and humanities not elsewhere classified',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0299',
    _type: 'IscedField',
    _slug: 'f0299-arts-and-humanities-not-elsewhere-classified',
    _published: false,
    name: 'Arts and humanities not elsewhere classified',
    codePath: ['F02', '9', '9'],
    code: 'F0299',
    description: 'Arts and humanities not elsewhere classified',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F03',
    _type: 'IscedField',
    _slug: 'f03-social-sciences-journalism-and-information',
    _published: true,
    name: 'Social sciences, journalism and information',
    codePath: ['F03'],
    code: 'F03',
    description: 'Social sciences, journalism and information',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F030',
    _type: 'IscedField',
    _slug: 'f030-social-sciences-journalism-and-information-not-further-defined',
    _published: false,
    name: 'Social sciences, journalism and information not further defined',
    codePath: ['F03', '0'],
    code: 'F030',
    description: 'Social sciences, journalism and information not further defined',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0300',
    _type: 'IscedField',
    _slug: 'f0300-social-sciences-journalism-and-information-not-further-defined',
    _published: false,
    name: 'Social sciences, journalism and information not further defined',
    codePath: ['F03', '0', '0'],
    code: 'F0300',
    description: 'Social sciences, journalism and information not further defined',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F031',
    _type: 'IscedField',
    _slug: 'f031-social-and-behavioural-sciences',
    _published: true,
    name: 'Social and behavioural sciences',
    codePath: ['F03', '1'],
    code: 'F031',
    description: 'Social and behavioural sciences',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0310',
    _type: 'IscedField',
    _slug: 'f0310-social-and-behavioural-sciences-not-further-defined',
    _published: false,
    name: 'Social and behavioural sciences not further defined',
    codePath: ['F03', '1', '0'],
    code: 'F0310',
    description: 'Social and behavioural sciences not further defined',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0311',
    _type: 'IscedField',
    _slug: 'f0311-economics',
    _published: true,
    name: 'Economics',
    codePath: ['F03', '1', '1'],
    code: 'F0311',
    description: 'Economics',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0312',
    _type: 'IscedField',
    _slug: 'f0312-political-sciences-and-civics',
    _published: true,
    name: 'Political sciences and civics',
    codePath: ['F03', '1', '2'],
    code: 'F0312',
    description: 'Political sciences and civics',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0313',
    _type: 'IscedField',
    _slug: 'f0313-psychology',
    _published: true,
    name: 'Psychology',
    codePath: ['F03', '1', '3'],
    code: 'F0313',
    description: 'Psychology',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0314',
    _type: 'IscedField',
    _slug: 'f0314-sociology-and-cultural-studies',
    _published: true,
    name: 'Sociology and cultural studies',
    codePath: ['F03', '1', '4'],
    code: 'F0314',
    description: 'Sociology and cultural studies',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0319',
    _type: 'IscedField',
    _slug: 'f0319-social-and-behavioural-sciences-not-elsewhere-classified',
    _published: false,
    name: 'Social and behavioural sciences not elsewhere classified',
    codePath: ['F03', '1', '9'],
    code: 'F0319',
    description: 'Social and behavioural sciences not elsewhere classified',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F032',
    _type: 'IscedField',
    _slug: 'f032-journalism-and-information',
    _published: true,
    name: 'Journalism and information',
    codePath: ['F03', '2'],
    code: 'F032',
    description: 'Journalism and information',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0320',
    _type: 'IscedField',
    _slug: 'f0320-journalism-and-information-not-further-defined',
    _published: false,
    name: 'Journalism and information not further defined',
    codePath: ['F03', '2', '0'],
    code: 'F0320',
    description: 'Journalism and information not further defined',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0321',
    _type: 'IscedField',
    _slug: 'f0321-journalism-and-reporting',
    _published: true,
    name: 'Journalism and reporting',
    codePath: ['F03', '2', '1'],
    code: 'F0321',
    description: 'Journalism and reporting',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0322',
    _type: 'IscedField',
    _slug: 'f0322-library-information-and-archival-studies',
    _published: true,
    name: 'Library, information and archival studies',
    codePath: ['F03', '2', '2'],
    code: 'F0322',
    description: 'Library, information and archival studies',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0329',
    _type: 'IscedField',
    _slug: 'f0329-journalism-and-information-not-elsewhere-classified',
    _published: false,
    name: 'Journalism and information not elsewhere classified',
    codePath: ['F03', '2', '9'],
    code: 'F0329',
    description: 'Journalism and information not elsewhere classified',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F038',
    _type: 'IscedField',
    _slug: 'f038-inter-disciplinary-programmes-and-qualifications-involving-social-sciences-journalism-and-information',
    _published: true,
    name: 'Inter-disciplinary programmes and qualifications involving social sciences, journalism and information',
    codePath: ['F03', '8'],
    code: 'F038',
    description:
      'Inter-disciplinary programmes and qualifications involving social sciences, journalism and information',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0388',
    _type: 'IscedField',
    _slug:
      'f0388-inter-disciplinary-programmes-and-qualifications-involving-social-sciences-journalism-and-information',
    _published: false,
    name: 'Inter-disciplinary programmes and qualifications involving social sciences, journalism and information',
    codePath: ['F03', '8', '8'],
    code: 'F0388',
    description:
      'Inter-disciplinary programmes and qualifications involving social sciences, journalism and information',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F039',
    _type: 'IscedField',
    _slug: 'f039-social-sciences-journalism-and-information-not-elsewhere-classified',
    _published: false,
    name: 'Social sciences, journalism and information not elsewhere classified',
    codePath: ['F03', '9'],
    code: 'F039',
    description: 'Social sciences, journalism and information not elsewhere classified',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0399',
    _type: 'IscedField',
    _slug: 'f0399-social-sciences-journalism-and-information-not-elsewhere-classified',
    _published: false,
    name: 'Social sciences, journalism and information not elsewhere classified',
    codePath: ['F03', '9', '9'],
    code: 'F0399',
    description: 'Social sciences, journalism and information not elsewhere classified',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F04',
    _type: 'IscedField',
    _slug: 'f04-business-administration-and-law',
    _published: true,
    name: 'Business, administration and law',
    codePath: ['F04'],
    code: 'F04',
    description: 'Business, administration and law',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F040',
    _type: 'IscedField',
    _slug: 'f040-business-administration-and-law-not-further-defined',
    _published: false,
    name: 'Business, administration and law not further defined',
    codePath: ['F04', '0'],
    code: 'F040',
    description: 'Business, administration and law not further defined',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0400',
    _type: 'IscedField',
    _slug: 'f0400-business-administration-and-law-not-further-defined',
    _published: false,
    name: 'Business, administration and law not further defined',
    codePath: ['F04', '0', '0'],
    code: 'F0400',
    description: 'Business, administration and law not further defined',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F041',
    _type: 'IscedField',
    _slug: 'f041-business-and-administration',
    _published: true,
    name: 'Business and administration',
    codePath: ['F04', '1'],
    code: 'F041',
    description: 'Business and administration',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0410',
    _type: 'IscedField',
    _slug: 'f0410-business-and-administration-not-further-defined',
    _published: false,
    name: 'Business and administration not further defined',
    codePath: ['F04', '1', '0'],
    code: 'F0410',
    description: 'Business and administration not further defined',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0411',
    _type: 'IscedField',
    _slug: 'f0411-accounting-and-taxation',
    _published: true,
    name: 'Accounting and taxation',
    codePath: ['F04', '1', '1'],
    code: 'F0411',
    description: 'Accounting and taxation',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0412',
    _type: 'IscedField',
    _slug: 'f0412-finance-banking-and-insurance',
    _published: true,
    name: 'Finance, banking and insurance',
    codePath: ['F04', '1', '2'],
    code: 'F0412',
    description: 'Finance, banking and insurance',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0413',
    _type: 'IscedField',
    _slug: 'f0413-management-and-administration',
    _published: true,
    name: 'Management and administration',
    codePath: ['F04', '1', '3'],
    code: 'F0413',
    description: 'Management and administration',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0414',
    _type: 'IscedField',
    _slug: 'f0414-marketing-and-advertising',
    _published: true,
    name: 'Marketing and advertising',
    codePath: ['F04', '1', '4'],
    code: 'F0414',
    description: 'Marketing and advertising',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0415',
    _type: 'IscedField',
    _slug: 'f0415-secretarial-and-office-work',
    _published: true,
    name: 'Secretarial and office work',
    codePath: ['F04', '1', '5'],
    code: 'F0415',
    description: 'Secretarial and office work',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0416',
    _type: 'IscedField',
    _slug: 'f0416-wholesale-and-retail-sales',
    _published: true,
    name: 'Wholesale and retail sales',
    codePath: ['F04', '1', '6'],
    code: 'F0416',
    description: 'Wholesale and retail sales',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0417',
    _type: 'IscedField',
    _slug: 'f0417-work-skills',
    _published: true,
    name: 'Work skills',
    codePath: ['F04', '1', '7'],
    code: 'F0417',
    description: 'Work skills',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0419',
    _type: 'IscedField',
    _slug: 'f0419-business-and-administration-not-elsewhere-classified',
    _published: false,
    name: 'Business and administration not elsewhere classified',
    codePath: ['F04', '1', '9'],
    code: 'F0419',
    description: 'Business and administration not elsewhere classified',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F042',
    _type: 'IscedField',
    _slug: 'f042-law',
    _published: true,
    name: 'Law',
    codePath: ['F04', '2'],
    code: 'F042',
    description: 'Law',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0421',
    _type: 'IscedField',
    _slug: 'f0421-law',
    _published: false,
    name: 'Law',
    codePath: ['F04', '2', '1'],
    code: 'F0421',
    description: 'Law',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F048',
    _type: 'IscedField',
    _slug: 'f048-inter-disciplinary-programmes-and-qualifications-involving-business-administration-and-law',
    _published: true,
    name: 'Inter-disciplinary programmes and qualifications involving business, administration and law',
    codePath: ['F04', '8'],
    code: 'F048',
    description: 'Inter-disciplinary programmes and qualifications involving business, administration and law',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0488',
    _type: 'IscedField',
    _slug: 'f0488-inter-disciplinary-programmes-and-qualifications-involving-business-administration-and-law',
    _published: false,
    name: 'Inter-disciplinary programmes and qualifications involving business, administration and law',
    codePath: ['F04', '8', '8'],
    code: 'F0488',
    description: 'Inter-disciplinary programmes and qualifications involving business, administration and law',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F049',
    _type: 'IscedField',
    _slug: 'f049-business-administration-and-law-not-elsewhere-classified',
    _published: false,
    name: 'Business, administration and law not elsewhere classified',
    codePath: ['F04', '9'],
    code: 'F049',
    description: 'Business, administration and law not elsewhere classified',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0499',
    _type: 'IscedField',
    _slug: 'f0499-business-administration-and-law-not-elsewhere-classified',
    _published: false,
    name: 'Business, administration and law not elsewhere classified',
    codePath: ['F04', '9', '9'],
    code: 'F0499',
    description: 'Business, administration and law not elsewhere classified',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F05',
    _type: 'IscedField',
    _slug: 'f05-natural-sciences-mathematics-and-statistics',
    _published: true,
    name: 'Natural sciences, mathematics and statistics',
    codePath: ['F05'],
    code: 'F05',
    description: 'Natural sciences, mathematics and statistics',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F050',
    _type: 'IscedField',
    _slug: 'f050-natural-sciences-mathematics-and-statistics-not-further-defined',
    _published: false,
    name: 'Natural sciences, mathematics and statistics not further defined',
    codePath: ['F05', '0'],
    code: 'F050',
    description: 'Natural sciences, mathematics and statistics not further defined',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0500',
    _type: 'IscedField',
    _slug: 'f0500-natural-sciences-mathematics-and-statistics-not-further-defined',
    _published: false,
    name: 'Natural sciences, mathematics and statistics not further defined',
    codePath: ['F05', '0', '0'],
    code: 'F0500',
    description: 'Natural sciences, mathematics and statistics not further defined',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F051',
    _type: 'IscedField',
    _slug: 'f051-biological-and-related-sciences',
    _published: true,
    name: 'Biological and related sciences',
    codePath: ['F05', '1'],
    code: 'F051',
    description: 'Biological and related sciences',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0510',
    _type: 'IscedField',
    _slug: 'f0510-biological-and-related-sciences-not-further-defined',
    _published: false,
    name: 'Biological and related sciences not further defined',
    codePath: ['F05', '1', '0'],
    code: 'F0510',
    description: 'Biological and related sciences not further defined',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0511',
    _type: 'IscedField',
    _slug: 'f0511-biology',
    _published: true,
    name: 'Biology',
    codePath: ['F05', '1', '1'],
    code: 'F0511',
    description: 'Biology',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0512',
    _type: 'IscedField',
    _slug: 'f0512-biochemistry',
    _published: true,
    name: 'Biochemistry',
    codePath: ['F05', '1', '2'],
    code: 'F0512',
    description: 'Biochemistry',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0519',
    _type: 'IscedField',
    _slug: 'f0519-biological-and-related-sciences-not-elsewhere-classified',
    _published: false,
    name: 'Biological and related sciences not elsewhere classified',
    codePath: ['F05', '1', '9'],
    code: 'F0519',
    description: 'Biological and related sciences not elsewhere classified',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F052',
    _type: 'IscedField',
    _slug: 'f052-environment',
    _published: true,
    name: 'Environment',
    codePath: ['F05', '2'],
    code: 'F052',
    description: 'Environment',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0520',
    _type: 'IscedField',
    _slug: 'f0520-environment-not-further-defined',
    _published: false,
    name: 'Environment not further defined',
    codePath: ['F05', '2', '0'],
    code: 'F0520',
    description: 'Environment not further defined',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0521',
    _type: 'IscedField',
    _slug: 'f0521-environmental-sciences',
    _published: true,
    name: 'Environmental sciences',
    codePath: ['F05', '2', '1'],
    code: 'F0521',
    description: 'Environmental sciences',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0522',
    _type: 'IscedField',
    _slug: 'f0522-natural-environments-and-wildlife',
    _published: true,
    name: 'Natural environments and wildlife',
    codePath: ['F05', '2', '2'],
    code: 'F0522',
    description: 'Natural environments and wildlife',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0529',
    _type: 'IscedField',
    _slug: 'f0529-environment-not-elsewhere-classified',
    _published: false,
    name: 'Environment not elsewhere classified',
    codePath: ['F05', '2', '9'],
    code: 'F0529',
    description: 'Environment not elsewhere classified',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F053',
    _type: 'IscedField',
    _slug: 'f053-physical-sciences',
    _published: true,
    name: 'Physical sciences',
    codePath: ['F05', '3'],
    code: 'F053',
    description: 'Physical sciences',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0530',
    _type: 'IscedField',
    _slug: 'f0530-physical-sciences-not-further-defined',
    _published: false,
    name: 'Physical sciences not further defined',
    codePath: ['F05', '3', '0'],
    code: 'F0530',
    description: 'Physical sciences not further defined',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0531',
    _type: 'IscedField',
    _slug: 'f0531-chemistry',
    _published: true,
    name: 'Chemistry',
    codePath: ['F05', '3', '1'],
    code: 'F0531',
    description: 'Chemistry',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0532',
    _type: 'IscedField',
    _slug: 'f0532-earth-sciences',
    _published: true,
    name: 'Earth sciences',
    codePath: ['F05', '3', '2'],
    code: 'F0532',
    description: 'Earth sciences',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0533',
    _type: 'IscedField',
    _slug: 'f0533-physics',
    _published: true,
    name: 'Physics',
    codePath: ['F05', '3', '3'],
    code: 'F0533',
    description: 'Physics',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0539',
    _type: 'IscedField',
    _slug: 'f0539-physical-sciences-not-elsewhere-classified',
    _published: false,
    name: 'Physical sciences not elsewhere classified',
    codePath: ['F05', '3', '9'],
    code: 'F0539',
    description: 'Physical sciences not elsewhere classified',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F054',
    _type: 'IscedField',
    _slug: 'f054-mathematics-and-statistics',
    _published: true,
    name: 'Mathematics and statistics',
    codePath: ['F05', '4'],
    code: 'F054',
    description: 'Mathematics and statistics',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0540',
    _type: 'IscedField',
    _slug: 'f0540-mathematics-and-statistics-not-further-defined',
    _published: false,
    name: 'Mathematics and statistics not further defined',
    codePath: ['F05', '4', '0'],
    code: 'F0540',
    description: 'Mathematics and statistics not further defined',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0541',
    _type: 'IscedField',
    _slug: 'f0541-mathematics',
    _published: true,
    name: 'Mathematics',
    codePath: ['F05', '4', '1'],
    code: 'F0541',
    description: 'Mathematics',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0542',
    _type: 'IscedField',
    _slug: 'f0542-statistics',
    _published: true,
    name: 'Statistics',
    codePath: ['F05', '4', '2'],
    code: 'F0542',
    description: 'Statistics',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F058',
    _type: 'IscedField',
    _slug:
      'f058-inter-disciplinary-programmes-and-qualifications-involving-natural-sciences-mathematics-and-statistics',
    _published: true,
    name: 'Inter-disciplinary programmes and qualifications involving natural sciences, mathematics and statistics',
    codePath: ['F05', '8'],
    code: 'F058',
    description:
      'Inter-disciplinary programmes and qualifications involving natural sciences, mathematics and statistics',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0588',
    _type: 'IscedField',
    _slug:
      'f0588-inter-disciplinary-programmes-and-qualifications-involving-natural-sciences-mathematics-and-statistics',
    _published: false,
    name: 'Inter-disciplinary programmes and qualifications involving natural sciences, mathematics and statistics',
    codePath: ['F05', '8', '8'],
    code: 'F0588',
    description:
      'Inter-disciplinary programmes and qualifications involving natural sciences, mathematics and statistics',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F059',
    _type: 'IscedField',
    _slug: 'f059-natural-sciences-mathematics-and-statistics-not-elsewhere-classified',
    _published: false,
    name: 'Natural sciences, mathematics and statistics not elsewhere classified',
    codePath: ['F05', '9'],
    code: 'F059',
    description: 'Natural sciences, mathematics and statistics not elsewhere classified',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0599',
    _type: 'IscedField',
    _slug: 'f0599-natural-sciences-mathematics-and-statistics-not-elsewhere-classified',
    _published: false,
    name: 'Natural sciences, mathematics and statistics not elsewhere classified',
    codePath: ['F05', '9', '9'],
    code: 'F0599',
    description: 'Natural sciences, mathematics and statistics not elsewhere classified',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F06',
    _type: 'IscedField',
    _slug: 'f06-information-and-communication-technologies',
    _published: true,
    name: 'Information and Communication Technologies',
    codePath: ['F06'],
    code: 'F06',
    description: 'Information and Communication Technologies',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F061',
    _type: 'IscedField',
    _slug: 'f061-information-and-communication-technologies',
    _published: false,
    name: 'Information and Communication Technologies',
    codePath: ['F06', '1'],
    code: 'F061',
    description: 'Information and Communication Technologies',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0610',
    _type: 'IscedField',
    _slug: 'f0610-information-and-communication-technologies-not-further-defined',
    _published: false,
    name: 'Information and Communication Technologies not further defined',
    codePath: ['F06', '1', '0'],
    code: 'F0610',
    description: 'Information and Communication Technologies not further defined',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0611',
    _type: 'IscedField',
    _slug: 'f0611-computer-use',
    _published: true,
    name: 'Computer use',
    codePath: ['F06', '1', '1'],
    code: 'F0611',
    description: 'Computer use',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0612',
    _type: 'IscedField',
    _slug: 'f0612-database-and-network-design-and-administration',
    _published: true,
    name: 'Database and network design and administration',
    codePath: ['F06', '1', '2'],
    code: 'F0612',
    description: 'Database and network design and administration',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0613',
    _type: 'IscedField',
    _slug: 'f0613-software-and-applications-development-and-analysis',
    _published: true,
    name: 'Software and applications development and analysis',
    codePath: ['F06', '1', '3'],
    code: 'F0613',
    description: 'Software and applications development and analysis',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0619',
    _type: 'IscedField',
    _slug: 'f0619-information-and-communication-technologies-not-elsewhere-classified',
    _published: false,
    name: 'Information and Communication Technologies not elsewhere classified',
    codePath: ['F06', '1', '9'],
    code: 'F0619',
    description: 'Information and Communication Technologies not elsewhere classified',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F068',
    _type: 'IscedField',
    _slug: 'f068-inter-disciplinary-programmes-and-qualifications-involving-information-and-communication-technologies',
    _published: true,
    name: 'Inter-disciplinary programmes and qualifications involving information and Communication Technologies',
    codePath: ['F06', '8'],
    code: 'F068',
    description:
      'Inter-disciplinary programmes and qualifications involving information and Communication Technologies',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0688',
    _type: 'IscedField',
    _slug:
      'f0688-inter-disciplinary-programmes-and-qualifications-involving-information-and-communication-technologies',
    _published: false,
    name: 'Inter-disciplinary programmes and qualifications involving information and Communication Technologies',
    codePath: ['F06', '8', '8'],
    code: 'F0688',
    description:
      'Inter-disciplinary programmes and qualifications involving information and Communication Technologies',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F07',
    _type: 'IscedField',
    _slug: 'f07-engineering-manufacturing-and-construction',
    _published: true,
    name: 'Engineering, manufacturing and construction',
    codePath: ['F07'],
    code: 'F07',
    description: 'Engineering, manufacturing and construction',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F070',
    _type: 'IscedField',
    _slug: 'f070-engineering-manufacturing-and-construction-not-further-defined',
    _published: false,
    name: 'Engineering, manufacturing and construction not further defined',
    codePath: ['F07', '0'],
    code: 'F070',
    description: 'Engineering, manufacturing and construction not further defined',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0700',
    _type: 'IscedField',
    _slug: 'f0700-engineering-manufacturing-and-construction-not-further-defined',
    _published: false,
    name: 'Engineering, manufacturing and construction not further defined',
    codePath: ['F07', '0', '0'],
    code: 'F0700',
    description: 'Engineering, manufacturing and construction not further defined',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F071',
    _type: 'IscedField',
    _slug: 'f071-engineering-and-engineering-trades',
    _published: true,
    name: 'Engineering and engineering trades',
    codePath: ['F07', '1'],
    code: 'F071',
    description: 'Engineering and engineering trades',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0710',
    _type: 'IscedField',
    _slug: 'f0710-engineering-and-engineering-trades-not-further-defined',
    _published: false,
    name: 'Engineering and engineering trades not further defined',
    codePath: ['F07', '1', '0'],
    code: 'F0710',
    description: 'Engineering and engineering trades not further defined',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0711',
    _type: 'IscedField',
    _slug: 'f0711-chemical-engineering-and-processes',
    _published: true,
    name: 'Chemical engineering and processes',
    codePath: ['F07', '1', '1'],
    code: 'F0711',
    description: 'Chemical engineering and processes',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0712',
    _type: 'IscedField',
    _slug: 'f0712-environmental-protection-technology',
    _published: true,
    name: 'Environmental protection technology',
    codePath: ['F07', '1', '2'],
    code: 'F0712',
    description: 'Environmental protection technology',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0713',
    _type: 'IscedField',
    _slug: 'f0713-electricity-and-energy',
    _published: true,
    name: 'Electricity and energy',
    codePath: ['F07', '1', '3'],
    code: 'F0713',
    description: 'Electricity and energy',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0714',
    _type: 'IscedField',
    _slug: 'f0714-electronics-and-automation',
    _published: true,
    name: 'Electronics and automation',
    codePath: ['F07', '1', '4'],
    code: 'F0714',
    description: 'Electronics and automation',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0715',
    _type: 'IscedField',
    _slug: 'f0715-mechanics-and-metal-trades',
    _published: true,
    name: 'Mechanics and metal trades',
    codePath: ['F07', '1', '5'],
    code: 'F0715',
    description: 'Mechanics and metal trades',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0716',
    _type: 'IscedField',
    _slug: 'f0716-motor-vehicles-ships-and-aircraft',
    _published: true,
    name: 'Motor vehicles, ships and aircraft',
    codePath: ['F07', '1', '6'],
    code: 'F0716',
    description: 'Motor vehicles, ships and aircraft',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0719',
    _type: 'IscedField',
    _slug: 'f0719-engineering-and-engineering-trades-not-elsewhere-classified',
    _published: false,
    name: 'Engineering and engineering trades not elsewhere classified',
    codePath: ['F07', '1', '9'],
    code: 'F0719',
    description: 'Engineering and engineering trades not elsewhere classified',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F072',
    _type: 'IscedField',
    _slug: 'f072-manufacturing-and-processing',
    _published: true,
    name: 'Manufacturing and processing',
    codePath: ['F07', '2'],
    code: 'F072',
    description: 'Manufacturing and processing',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0720',
    _type: 'IscedField',
    _slug: 'f0720-manufacturing-and-processing-not-further-defined',
    _published: false,
    name: 'Manufacturing and processing not further defined',
    codePath: ['F07', '2', '0'],
    code: 'F0720',
    description: 'Manufacturing and processing not further defined',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0721',
    _type: 'IscedField',
    _slug: 'f0721-food-processing',
    _published: true,
    name: 'Food processing',
    codePath: ['F07', '2', '1'],
    code: 'F0721',
    description: 'Food processing',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0722',
    _type: 'IscedField',
    _slug: 'f0722-materials-glass-paper-plastic-and-wood',
    _published: true,
    name: 'Materials (glass, paper, plastic and wood)',
    codePath: ['F07', '2', '2'],
    code: 'F0722',
    description: 'Materials (glass, paper, plastic and wood)',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0723',
    _type: 'IscedField',
    _slug: 'f0723-textiles-clothes-footwear-and-leather',
    _published: true,
    name: 'Textiles (clothes, footwear and leather)',
    codePath: ['F07', '2', '3'],
    code: 'F0723',
    description: 'Textiles (clothes, footwear and leather)',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0724',
    _type: 'IscedField',
    _slug: 'f0724-mining-and-extraction',
    _published: true,
    name: 'Mining and extraction',
    codePath: ['F07', '2', '4'],
    code: 'F0724',
    description: 'Mining and extraction',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0729',
    _type: 'IscedField',
    _slug: 'f0729-manufacturing-and-processing-not-elsewhere-classified',
    _published: false,
    name: 'Manufacturing and processing not elsewhere classified',
    codePath: ['F07', '2', '9'],
    code: 'F0729',
    description: 'Manufacturing and processing not elsewhere classified',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F073',
    _type: 'IscedField',
    _slug: 'f073-architecture-and-construction',
    _published: true,
    name: 'Architecture and construction',
    codePath: ['F07', '3'],
    code: 'F073',
    description: 'Architecture and construction',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0730',
    _type: 'IscedField',
    _slug: 'f0730-architecture-and-construction-not-further-defined',
    _published: false,
    name: 'Architecture and construction not further defined',
    codePath: ['F07', '3', '0'],
    code: 'F0730',
    description: 'Architecture and construction not further defined',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0731',
    _type: 'IscedField',
    _slug: 'f0731-architecture-and-town-planning',
    _published: false,
    name: 'Architecture and town planning',
    codePath: ['F07', '3', '1'],
    code: 'F0731',
    description: 'Architecture and town planning',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0732',
    _type: 'IscedField',
    _slug: 'f0732-building-and-civil-engineering',
    _published: true,
    name: 'Building and civil engineering',
    codePath: ['F07', '3', '2'],
    code: 'F0732',
    description: 'Building and civil engineering',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F078',
    _type: 'IscedField',
    _slug: 'f078-inter-disciplinary-programmes-and-qualifications-involving-engineering-manufacturing-and-construction',
    _published: true,
    name: 'Inter-disciplinary programmes and qualifications involving engineering, manufacturing and construction',
    codePath: ['F07', '8'],
    code: 'F078',
    description:
      'Inter-disciplinary programmes and qualifications involving engineering, manufacturing and construction',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0788',
    _type: 'IscedField',
    _slug:
      'f0788-inter-disciplinary-programmes-and-qualifications-involving-engineering-manufacturing-and-construction',
    _published: false,
    name: 'Inter-disciplinary programmes and qualifications involving engineering, manufacturing and construction',
    codePath: ['F07', '8', '8'],
    code: 'F0788',
    description:
      'Inter-disciplinary programmes and qualifications involving engineering, manufacturing and construction',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F079',
    _type: 'IscedField',
    _slug: 'f079-engineering-manufacturing-and-construction-not-elsewhere-classified',
    _published: false,
    name: 'Engineering, manufacturing and construction not elsewhere classified',
    codePath: ['F07', '9'],
    code: 'F079',
    description: 'Engineering, manufacturing and construction not elsewhere classified',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0799',
    _type: 'IscedField',
    _slug: 'f0799-engineering-manufacturing-and-construction-not-elsewhere-classified',
    _published: false,
    name: 'Engineering, manufacturing and construction not elsewhere classified',
    codePath: ['F07', '9', '9'],
    code: 'F0799',
    description: 'Engineering, manufacturing and construction not elsewhere classified',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F08',
    _type: 'IscedField',
    _slug: 'f08-agriculture-forestry-fisheries-and-veterinary',
    _published: true,
    name: 'Agriculture, forestry, fisheries and veterinary',
    codePath: ['F08'],
    code: 'F08',
    description: 'Agriculture, forestry, fisheries and veterinary',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F080',
    _type: 'IscedField',
    _slug: 'f080-agriculture-forestry-fisheries-and-veterinary-not-further-defined',
    _published: false,
    name: 'Agriculture, forestry, fisheries and veterinary not further defined',
    codePath: ['F08', '0'],
    code: 'F080',
    description: 'Agriculture, forestry, fisheries and veterinary not further defined',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0800',
    _type: 'IscedField',
    _slug: 'f0800-agriculture-forestry-fisheries-and-veterinary-not-further-defined',
    _published: false,
    name: 'Agriculture, forestry, fisheries and veterinary not further defined',
    codePath: ['F08', '0', '0'],
    code: 'F0800',
    description: 'Agriculture, forestry, fisheries and veterinary not further defined',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F081',
    _type: 'IscedField',
    _slug: 'f081-agriculture',
    _published: true,
    name: 'Agriculture',
    codePath: ['F08', '1'],
    code: 'F081',
    description: 'Agriculture',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0810',
    _type: 'IscedField',
    _slug: 'f0810-agriculture-not-further-defined',
    _published: false,
    name: 'Agriculture not further defined',
    codePath: ['F08', '1', '0'],
    code: 'F0810',
    description: 'Agriculture not further defined',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0811',
    _type: 'IscedField',
    _slug: 'f0811-crop-and-livestock-production',
    _published: true,
    name: 'Crop and livestock production',
    codePath: ['F08', '1', '1'],
    code: 'F0811',
    description: 'Crop and livestock production',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0812',
    _type: 'IscedField',
    _slug: 'f0812-horticulture',
    _published: true,
    name: 'Horticulture',
    codePath: ['F08', '1', '2'],
    code: 'F0812',
    description: 'Horticulture',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0819',
    _type: 'IscedField',
    _slug: 'f0819-agriculture-not-elsewhere-classified',
    _published: false,
    name: 'Agriculture not elsewhere classified',
    codePath: ['F08', '1', '9'],
    code: 'F0819',
    description: 'Agriculture not elsewhere classified',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F082',
    _type: 'IscedField',
    _slug: 'f082-forestry',
    _published: true,
    name: 'Forestry',
    codePath: ['F08', '2'],
    code: 'F082',
    description: 'Forestry',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0821',
    _type: 'IscedField',
    _slug: 'f0821-forestry',
    _published: false,
    name: 'Forestry',
    codePath: ['F08', '2', '1'],
    code: 'F0821',
    description: 'Forestry',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F083',
    _type: 'IscedField',
    _slug: 'f083-fisheries',
    _published: true,
    name: 'Fisheries',
    codePath: ['F08', '3'],
    code: 'F083',
    description: 'Fisheries',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0831',
    _type: 'IscedField',
    _slug: 'f0831-fisheries',
    _published: false,
    name: 'Fisheries',
    codePath: ['F08', '3', '1'],
    code: 'F0831',
    description: 'Fisheries',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F084',
    _type: 'IscedField',
    _slug: 'f084-veterinary',
    _published: true,
    name: 'Veterinary',
    codePath: ['F08', '4'],
    code: 'F084',
    description: 'Veterinary',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0841',
    _type: 'IscedField',
    _slug: 'f0841-veterinary',
    _published: false,
    name: 'Veterinary',
    codePath: ['F08', '4', '1'],
    code: 'F0841',
    description: 'Veterinary',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F088',
    _type: 'IscedField',
    _slug:
      'f088-inter-disciplinary-programmes-and-qualifications-involving-agriculture-forestry-fisheries-and-veterinary',
    _published: true,
    name: 'Inter-disciplinary programmes and qualifications involving agriculture, forestry, fisheries and veterinary',
    codePath: ['F08', '8'],
    code: 'F088',
    description:
      'Inter-disciplinary programmes and qualifications involving agriculture, forestry, fisheries and veterinary',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0888',
    _type: 'IscedField',
    _slug:
      'f0888-inter-disciplinary-programmes-and-qualifications-involving-agriculture-forestry-fisheries-and-veterinary',
    _published: false,
    name: 'Inter-disciplinary programmes and qualifications involving agriculture, forestry, fisheries and veterinary',
    codePath: ['F08', '8', '8'],
    code: 'F0888',
    description:
      'Inter-disciplinary programmes and qualifications involving agriculture, forestry, fisheries and veterinary',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F089',
    _type: 'IscedField',
    _slug: 'f089-agriculture-forestry-fisheries-and-veterinary-not-elsewhere-classified',
    _published: false,
    name: 'Agriculture, forestry, fisheries and veterinary not elsewhere classified',
    codePath: ['F08', '9'],
    code: 'F089',
    description: 'Agriculture, forestry, fisheries and veterinary not elsewhere classified',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0899',
    _type: 'IscedField',
    _slug: 'f0899-agriculture-forestry-fisheries-and-veterinary-not-elsewhere-classified',
    _published: false,
    name: 'Agriculture, forestry, fisheries and veterinary not elsewhere classified',
    codePath: ['F08', '9', '9'],
    code: 'F0899',
    description: 'Agriculture, forestry, fisheries and veterinary not elsewhere classified',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F09',
    _type: 'IscedField',
    _slug: 'f09-health-and-welfare',
    _published: true,
    name: 'Health and welfare',
    codePath: ['F09'],
    code: 'F09',
    description: 'Health and welfare',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F090',
    _type: 'IscedField',
    _slug: 'f090-health-and-welfare-not-further-defined',
    _published: false,
    name: 'Health and welfare not further defined',
    codePath: ['F09', '0'],
    code: 'F090',
    description: 'Health and welfare not further defined',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0900',
    _type: 'IscedField',
    _slug: 'f0900-health-and-welfare-not-further-defined',
    _published: false,
    name: 'Health and welfare not further defined',
    codePath: ['F09', '0', '0'],
    code: 'F0900',
    description: 'Health and welfare not further defined',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F091',
    _type: 'IscedField',
    _slug: 'f091-health',
    _published: true,
    name: 'Health',
    codePath: ['F09', '1'],
    code: 'F091',
    description: 'Health',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0910',
    _type: 'IscedField',
    _slug: 'f0910-health-not-further-defined',
    _published: false,
    name: 'Health not further defined',
    codePath: ['F09', '1', '0'],
    code: 'F0910',
    description: 'Health not further defined',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0911',
    _type: 'IscedField',
    _slug: 'f0911-dental-studies',
    _published: true,
    name: 'Dental studies',
    codePath: ['F09', '1', '1'],
    code: 'F0911',
    description: 'Dental studies',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0912',
    _type: 'IscedField',
    _slug: 'f0912-medicine',
    _published: true,
    name: 'Medicine',
    codePath: ['F09', '1', '2'],
    code: 'F0912',
    description: 'Medicine',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0913',
    _type: 'IscedField',
    _slug: 'f0913-nursing-and-midwifery',
    _published: true,
    name: 'Nursing and midwifery',
    codePath: ['F09', '1', '3'],
    code: 'F0913',
    description: 'Nursing and midwifery',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0914',
    _type: 'IscedField',
    _slug: 'f0914-medical-diagnostic-and-treatment-technology',
    _published: true,
    name: 'Medical diagnostic and treatment technology',
    codePath: ['F09', '1', '4'],
    code: 'F0914',
    description: 'Medical diagnostic and treatment technology',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0915',
    _type: 'IscedField',
    _slug: 'f0915-therapy-and-rehabilitation',
    _published: true,
    name: 'Therapy and rehabilitation',
    codePath: ['F09', '1', '5'],
    code: 'F0915',
    description: 'Therapy and rehabilitation',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0916',
    _type: 'IscedField',
    _slug: 'f0916-pharmacy',
    _published: true,
    name: 'Pharmacy',
    codePath: ['F09', '1', '6'],
    code: 'F0916',
    description: 'Pharmacy',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0917',
    _type: 'IscedField',
    _slug: 'f0917-traditional-and-complementary-medicine-and-therapy',
    _published: true,
    name: 'Traditional and complementary medicine and therapy',
    codePath: ['F09', '1', '7'],
    code: 'F0917',
    description: 'Traditional and complementary medicine and therapy',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0919',
    _type: 'IscedField',
    _slug: 'f0919-health-not-elsewhere-classified',
    _published: false,
    name: 'Health not elsewhere classified',
    codePath: ['F09', '1', '9'],
    code: 'F0919',
    description: 'Health not elsewhere classified',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F092',
    _type: 'IscedField',
    _slug: 'f092-welfare',
    _published: true,
    name: 'Welfare',
    codePath: ['F09', '2'],
    code: 'F092',
    description: 'Welfare',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0920',
    _type: 'IscedField',
    _slug: 'f0920-welfare-not-further-defined',
    _published: true,
    name: 'Welfare not further defined',
    codePath: ['F09', '2', '0'],
    code: 'F0920',
    description: 'Welfare not further defined',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0921',
    _type: 'IscedField',
    _slug: 'f0921-care-of-the-elderly-and-of-disabled-adults',
    _published: true,
    name: 'Care of the elderly and of disabled adults',
    codePath: ['F09', '2', '1'],
    code: 'F0921',
    description: 'Care of the elderly and of disabled adults',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0922',
    _type: 'IscedField',
    _slug: 'f0922-child-care-and-youth-services',
    _published: true,
    name: 'Child care and youth services',
    codePath: ['F09', '2', '2'],
    code: 'F0922',
    description: 'Child care and youth services',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0923',
    _type: 'IscedField',
    _slug: 'f0923-social-work-and-counselling',
    _published: true,
    name: 'Social work and counselling',
    codePath: ['F09', '2', '3'],
    code: 'F0923',
    description: 'Social work and counselling',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0929',
    _type: 'IscedField',
    _slug: 'f0929-welfare-not-elsewhere-classified',
    _published: false,
    name: 'Welfare not elsewhere classified',
    codePath: ['F09', '2', '9'],
    code: 'F0929',
    description: 'Welfare not elsewhere classified',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F098',
    _type: 'IscedField',
    _slug: 'f098-inter-disciplinary-programmes-and-qualifications-involving-health-and-welfare',
    _published: true,
    name: 'Inter-disciplinary programmes and qualifications involving health and welfare',
    codePath: ['F09', '8'],
    code: 'F098',
    description: 'Inter-disciplinary programmes and qualifications involving health and welfare',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0988',
    _type: 'IscedField',
    _slug: 'f0988-inter-disciplinary-programmes-and-qualifications-involving-health-and-welfare',
    _published: false,
    name: 'Inter-disciplinary programmes and qualifications involving health and welfare',
    codePath: ['F09', '8', '8'],
    code: 'F0988',
    description: 'Inter-disciplinary programmes and qualifications involving health and welfare',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F099',
    _type: 'IscedField',
    _slug: 'f099-health-and-welfare-not-elsewhere-classified',
    _published: false,
    name: 'Health and welfare not elsewhere classified',
    codePath: ['F09', '9'],
    code: 'F099',
    description: 'Health and welfare not elsewhere classified',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F0999',
    _type: 'IscedField',
    _slug: 'f0999-health-and-welfare-not-elsewhere-classified',
    _published: false,
    name: 'Health and welfare not elsewhere classified',
    codePath: ['F09', '9', '9'],
    code: 'F0999',
    description: 'Health and welfare not elsewhere classified',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F10',
    _type: 'IscedField',
    _slug: 'f10-services',
    _published: true,
    name: 'Services',
    codePath: ['F10'],
    code: 'F10',
    description: 'Services',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F100',
    _type: 'IscedField',
    _slug: 'f100-services-not-further-defined',
    _published: false,
    name: 'Services not further defined',
    codePath: ['F10', '0'],
    code: 'F100',
    description: 'Services not further defined',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F1000',
    _type: 'IscedField',
    _slug: 'f1000-services-not-further-defined',
    _published: false,
    name: 'Services not further defined',
    codePath: ['F10', '0', '0'],
    code: 'F1000',
    description: 'Services not further defined',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F101',
    _type: 'IscedField',
    _slug: 'f101-personal-services',
    _published: true,
    name: 'Personal services',
    codePath: ['F10', '1'],
    code: 'F101',
    description: 'Personal services',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F1010',
    _type: 'IscedField',
    _slug: 'f1010-personal-services-not-further-defined',
    _published: false,
    name: 'Personal services not further defined',
    codePath: ['F10', '1', '0'],
    code: 'F1010',
    description: 'Personal services not further defined',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F1011',
    _type: 'IscedField',
    _slug: 'f1011-domestic-services',
    _published: true,
    name: 'Domestic services',
    codePath: ['F10', '1', '1'],
    code: 'F1011',
    description: 'Domestic services',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F1012',
    _type: 'IscedField',
    _slug: 'f1012-hair-and-beauty-services',
    _published: true,
    name: 'Hair and beauty services',
    codePath: ['F10', '1', '2'],
    code: 'F1012',
    description: 'Hair and beauty services',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F1013',
    _type: 'IscedField',
    _slug: 'f1013-hotel-restaurants-and-catering',
    _published: true,
    name: 'Hotel, restaurants and catering',
    codePath: ['F10', '1', '3'],
    code: 'F1013',
    description: 'Hotel, restaurants and catering',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F1014',
    _type: 'IscedField',
    _slug: 'f1014-sports',
    _published: true,
    name: 'Sports',
    codePath: ['F10', '1', '4'],
    code: 'F1014',
    description: 'Sports',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F1015',
    _type: 'IscedField',
    _slug: 'f1015-travel-tourism-and-leisure',
    _published: true,
    name: 'Travel, tourism and leisure',
    codePath: ['F10', '1', '5'],
    code: 'F1015',
    description: 'Travel, tourism and leisure',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F1019',
    _type: 'IscedField',
    _slug: 'f1019-personal-services-not-elsewhere-classified',
    _published: false,
    name: 'Personal services not elsewhere classified',
    codePath: ['F10', '1', '9'],
    code: 'F1019',
    description: 'Personal services not elsewhere classified',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F102',
    _type: 'IscedField',
    _slug: 'f102-hygiene-and-occupational-health-services',
    _published: true,
    name: 'Hygiene and occupational health services',
    codePath: ['F10', '2'],
    code: 'F102',
    description: 'Hygiene and occupational health services',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F1020',
    _type: 'IscedField',
    _slug: 'f1020-hygiene-and-occupational-health-services-not-further-defined',
    _published: true,
    name: 'Hygiene and occupational health services not further defined',
    codePath: ['F10', '2', '0'],
    code: 'F1020',
    description: 'Hygiene and occupational health services not further defined',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F1021',
    _type: 'IscedField',
    _slug: 'f1021-community-sanitation',
    _published: true,
    name: 'Community sanitation',
    codePath: ['F10', '2', '1'],
    code: 'F1021',
    description: 'Community sanitation',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F1022',
    _type: 'IscedField',
    _slug: 'f1022-occupational-health-and-safety',
    _published: true,
    name: 'Occupational health and safety',
    codePath: ['F10', '2', '2'],
    code: 'F1022',
    description: 'Occupational health and safety',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F1029',
    _type: 'IscedField',
    _slug: 'f1029-hygiene-and-occupational-health-services-not-elsewhere-classified',
    _published: false,
    name: 'Hygiene and occupational health services not elsewhere classified',
    codePath: ['F10', '2', '9'],
    code: 'F1029',
    description: 'Hygiene and occupational health services not elsewhere classified',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F103',
    _type: 'IscedField',
    _slug: 'f103-security-services',
    _published: true,
    name: 'Security services',
    codePath: ['F10', '3'],
    code: 'F103',
    description: 'Security services',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F1030',
    _type: 'IscedField',
    _slug: 'f1030-security-services-not-further-defined',
    _published: false,
    name: 'Security services not further defined',
    codePath: ['F10', '3', '0'],
    code: 'F1030',
    description: 'Security services not further defined',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F1031',
    _type: 'IscedField',
    _slug: 'f1031-military-and-defence',
    _published: true,
    name: 'Military and defence',
    codePath: ['F10', '3', '1'],
    code: 'F1031',
    description: 'Military and defence',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F1032',
    _type: 'IscedField',
    _slug: 'f1032-protection-of-persons-and-property',
    _published: true,
    name: 'Protection of persons and property',
    codePath: ['F10', '3', '2'],
    code: 'F1032',
    description: 'Protection of persons and property',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F1039',
    _type: 'IscedField',
    _slug: 'f1039-security-services-not-elsewhere-classified',
    _published: false,
    name: 'Security services not elsewhere classified',
    codePath: ['F10', '3', '9'],
    code: 'F1039',
    description: 'Security services not elsewhere classified',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F104',
    _type: 'IscedField',
    _slug: 'f104-transport-services',
    _published: true,
    name: 'Transport services',
    codePath: ['F10', '4'],
    code: 'F104',
    description: 'Transport services',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F1041',
    _type: 'IscedField',
    _slug: 'f1041-transport-services',
    _published: false,
    name: 'Transport services',
    codePath: ['F10', '4', '1'],
    code: 'F1041',
    description: 'Transport services',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F108',
    _type: 'IscedField',
    _slug: 'f108-inter-disciplinary-programmes-and-qualifications-involving-services',
    _published: true,
    name: 'Inter-disciplinary programmes and qualifications involving services',
    codePath: ['F10', '8'],
    code: 'F108',
    description: 'Inter-disciplinary programmes and qualifications involving services',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F1088',
    _type: 'IscedField',
    _slug: 'f1088-inter-disciplinary-programmes-and-qualifications-involving-services',
    _published: false,
    name: 'Inter-disciplinary programmes and qualifications involving services',
    codePath: ['F10', '8', '8'],
    code: 'F1088',
    description: 'Inter-disciplinary programmes and qualifications involving services',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F109',
    _type: 'IscedField',
    _slug: 'f109-services-not-elsewhere-classified',
    _published: false,
    name: 'Services not elsewhere classified',
    codePath: ['F10', '9'],
    code: 'F109',
    description: 'Services not elsewhere classified',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'F1099',
    _type: 'IscedField',
    _slug: 'f1099-services-not-elsewhere-classified',
    _published: false,
    name: 'Services not elsewhere classified',
    codePath: ['F10', '9', '9'],
    code: 'F1099',
    description: 'Services not elsewhere classified',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
]
export default _
