// @index(['./**/*.stories.*'], f => `export * as ${f.name.replace('.stories','Stories').replace('.props','')} from '${f.path}${f.ext==='.tsx'?'.js':f.ext==='.mts'?'.mjs':f.ext}'`)
export * as CardStories from './webapp/ui/components/atoms/Card/Card.stories.js'
export * as ColorpickerStories from './webapp/ui/components/atoms/Colorpicker/Colorpicker.stories.js'
export * as DropdownStories from './webapp/ui/components/atoms/Dropdown/stories/Dropdown.stories.js'
export * as DropdownPropsStories from './webapp/ui/components/atoms/Dropdown/stories/DropdownProps.stories.props.js'
export * as DropdownUtilStories from './webapp/ui/components/atoms/Dropdown/stories/DropdownUtil.stories.mjs'
export * as FileUploaderStories from './webapp/ui/components/atoms/FileUploader/FileUploader.stories.js'
export * as FloatingMenuStories from './webapp/ui/components/atoms/FloatingMenu/FloatingMenu.stories.js'
export * as InputTextFieldStories from './webapp/ui/components/atoms/InputTextField/InputTextField.stories.js'
export * as LoadingStories from './webapp/ui/components/atoms/Loading/Loading.stories.js'
export * as ModalStories from './webapp/ui/components/atoms/Modal/Modal.stories.js'
export * as PrimaryButtonStories from './webapp/ui/components/atoms/PrimaryButton/PrimaryButton.stories.js'
export * as RoundButtonStories from './webapp/ui/components/atoms/RoundButton/RoundButton.stories.js'
export * as SearchboxStories from './webapp/ui/components/atoms/Searchbox/Searchbox.stories.js'
export * as SecondaryButtonStories from './webapp/ui/components/atoms/SecondaryButton/SecondaryButton.stories.js'
export * as SimpleDropdownStories from './webapp/ui/components/atoms/SimpleDropdown/SimpleDropdown.stories.js'
export * as SnackbarStories from './webapp/ui/components/atoms/Snackbar/Snackbar.stories.js'
export * as SwitchStories from './webapp/ui/components/atoms/Switch/Switch.stories.js'
export * as TertiaryButtonStories from './webapp/ui/components/atoms/TertiaryButton/TertiaryButton.stories.js'
export * as AddToCollectionsCardStories from './webapp/ui/components/molecules/cards/AddToCollectionsCard/AddToCollectionsCard.stories.props.js'
export * as ImageContainerStories from './webapp/ui/components/molecules/ImageContainer/ImageContainer.stories.js'
export * as HeaderStories from './webapp/ui/components/organisms/Header/Standard/Header.stories.props.js'
export * as SearchImageStories from './webapp/ui/components/organisms/SearchImage/SearchImage.stories.js'
// @endindex
