export default [
  {
    _key: 'F1015',
    codePath: ['F10', '1', '5'],
    name: 'Travel, tourism and leisure',
    published: true,
  },
  {
    _key: 'F1010',
    codePath: ['F10', '1', '0'],
    name: 'Personal services not further defined',
    published: false,
  },
  {
    _key: 'F100',
    codePath: ['F10', '0'],
    name: 'Services not further defined',
    published: false,
  },
  {
    _key: 'F08',
    codePath: ['F08'],
    name: 'Agriculture, forestry, fisheries and veterinary',
    published: true,
  },
  {
    _key: 'F0533',
    codePath: ['F05', '3', '3'],
    name: 'Physics',
    published: true,
  },
  {
    _key: 'F0988',
    codePath: ['F09', '8', '8'],
    name: 'Inter-disciplinary programmes and qualifications involving health and welfare',
    published: false,
  },
  {
    _key: 'F0929',
    codePath: ['F09', '2', '9'],
    name: 'Welfare not elsewhere classified',
    published: false,
  },
  {
    _key: 'F0922',
    codePath: ['F09', '2', '2'],
    name: 'Child care and youth services',
    published: true,
  },
  {
    _key: 'F0529',
    codePath: ['F05', '2', '9'],
    name: 'Environment not elsewhere classified',
    published: false,
  },
  {
    _key: 'F0421',
    codePath: ['F04', '2', '1'],
    name: 'Law',
    published: false,
  },
  {
    _key: 'F0920',
    codePath: ['F09', '2', '0'],
    name: 'Welfare not further defined',
    published: true,
  },
  {
    _key: 'F0416',
    codePath: ['F04', '1', '6'],
    name: 'Wholesale and retail sales',
    published: true,
  },
  {
    _key: 'F0919',
    codePath: ['F09', '1', '9'],
    name: 'Health not elsewhere classified',
    published: false,
  },
  {
    _key: 'F0917',
    codePath: ['F09', '1', '7'],
    name: 'Traditional and complementary medicine and therapy',
    published: true,
  },
  {
    _key: 'F0915',
    codePath: ['F09', '1', '5'],
    name: 'Therapy and rehabilitation',
    published: true,
  },
  {
    _key: 'F0913',
    codePath: ['F09', '1', '3'],
    name: 'Nursing and midwifery',
    published: true,
  },
  {
    _key: 'F0214',
    codePath: ['F02', '1', '4'],
    name: 'Handicrafts',
    published: true,
  },
  {
    _key: 'F01',
    codePath: ['F01'],
    name: 'Education',
    published: true,
  },
  {
    _key: 'F1030',
    codePath: ['F10', '3', '0'],
    name: 'Security services not further defined',
    published: false,
  },
  {
    _key: 'F0821',
    codePath: ['F08', '2', '1'],
    name: 'Forestry',
    published: false,
  },
  {
    _key: 'F040',
    codePath: ['F04', '0'],
    name: 'Business, administration and law not further defined',
    published: false,
  },
  {
    _key: 'F022',
    codePath: ['F02', '2'],
    name: 'Humanities (except languages)',
    published: true,
  },
  {
    _key: 'F0031',
    codePath: ['F00', '3', '1'],
    name: 'Personal skills and development',
    published: false,
  },
  {
    _key: 'F098',
    codePath: ['F09', '8'],
    name: 'Inter-disciplinary programmes and qualifications involving health and welfare',
    published: true,
  },
  {
    _key: 'F0321',
    codePath: ['F03', '2', '1'],
    name: 'Journalism and reporting',
    published: true,
  },
  {
    _key: 'F0011',
    codePath: ['F00', '1', '1'],
    name: 'Basic programmes and qualifications',
    published: false,
  },
  {
    _key: 'F009',
    codePath: ['F00', '9'],
    name: 'Generic programmes and qualifications not elsewhere classified',
    published: false,
  },
  {
    _key: 'F0419',
    codePath: ['F04', '1', '9'],
    name: 'Business and administration not elsewhere classified',
    published: false,
  },
  {
    _key: 'F023',
    codePath: ['F02', '3'],
    name: 'Languages',
    published: true,
  },
  {
    _key: 'F0111',
    codePath: ['F01', '1', '1'],
    name: 'Education science',
    published: true,
  },
  {
    _key: 'F0499',
    codePath: ['F04', '9', '9'],
    name: 'Business, administration and law not elsewhere classified',
    published: false,
  },
  {
    _key: 'F0522',
    codePath: ['F05', '2', '2'],
    name: 'Natural environments and wildlife',
    published: true,
  },
  {
    _key: 'F0512',
    codePath: ['F05', '1', '2'],
    name: 'Biochemistry',
    published: true,
  },
  {
    _key: 'F0211',
    codePath: ['F02', '1', '1'],
    name: 'Audio-visual techniques and media production',
    published: true,
  },
  {
    _key: 'F018',
    codePath: ['F01', '8'],
    name: 'Inter-disciplinary programmes and qualifications involving education',
    published: true,
  },
  {
    _key: 'F0212',
    codePath: ['F02', '1', '2'],
    name: 'Fashion, interior and industrial design',
    published: true,
  },
  {
    _key: 'F0222',
    codePath: ['F02', '2', '2'],
    name: 'History and archaeology',
    published: true,
  },
  {
    _key: 'F0021',
    codePath: ['F00', '2', '1'],
    name: 'Literacy and numeracy',
    published: false,
  },
  {
    _key: 'F0711',
    codePath: ['F07', '1', '1'],
    name: 'Chemical engineering and processes',
    published: true,
  },
  {
    _key: 'F1000',
    codePath: ['F10', '0', '0'],
    name: 'Services not further defined',
    published: false,
  },
  {
    _key: 'F0200',
    codePath: ['F02', '0', '0'],
    name: 'Arts and humanities not further defined',
    published: false,
  },
  {
    _key: 'F0532',
    codePath: ['F05', '3', '2'],
    name: 'Earth sciences',
    published: true,
  },
  {
    _key: 'F0188',
    codePath: ['F01', '8', '8'],
    name: 'Inter-disciplinary programmes and qualifications involving education',
    published: false,
  },
  {
    _key: 'F0220',
    codePath: ['F02', '2', '0'],
    name: 'Humanities (except languages) not further defined',
    published: false,
  },
  {
    _key: 'F0413',
    codePath: ['F04', '1', '3'],
    name: 'Management and administration',
    published: true,
  },
  {
    _key: 'F0539',
    codePath: ['F05', '3', '9'],
    name: 'Physical sciences not elsewhere classified',
    published: false,
  },
  {
    _key: 'F0239',
    codePath: ['F02', '3', '9'],
    name: 'Languages not elsewhere classified',
    published: false,
  },
  {
    _key: 'F0112',
    codePath: ['F01', '1', '2'],
    name: 'Training for pre-school teachers',
    published: true,
  },
  {
    _key: 'F0417',
    codePath: ['F04', '1', '7'],
    name: 'Work skills',
    published: true,
  },
  {
    _key: 'F083',
    codePath: ['F08', '3'],
    name: 'Fisheries',
    published: true,
  },
  {
    _key: 'F0812',
    codePath: ['F08', '1', '2'],
    name: 'Horticulture',
    published: true,
  },
  {
    _key: 'F1032',
    codePath: ['F10', '3', '2'],
    name: 'Protection of persons and property',
    published: true,
  },
  {
    _key: 'F029',
    codePath: ['F02', '9'],
    name: 'Arts and humanities not elsewhere classified',
    published: false,
  },
  {
    _key: 'F0300',
    codePath: ['F03', '0', '0'],
    name: 'Social sciences, journalism and information not further defined',
    published: false,
  },
  {
    _key: 'F0221',
    codePath: ['F02', '2', '1'],
    name: 'Religion and theology',
    published: true,
  },
  {
    _key: 'F000',
    codePath: ['F00', '0'],
    name: 'Generic programmes and qualifications not further defined',
    published: false,
  },
  {
    _key: 'F0910',
    codePath: ['F09', '1', '0'],
    name: 'Health not further defined',
    published: false,
  },
  {
    _key: 'F0714',
    codePath: ['F07', '1', '4'],
    name: 'Electronics and automation',
    published: true,
  },
  {
    _key: 'F071',
    codePath: ['F07', '1'],
    name: 'Engineering and engineering trades',
    published: true,
  },
  {
    _key: 'F0213',
    codePath: ['F02', '1', '3'],
    name: 'Fine arts',
    published: true,
  },
  {
    _key: 'F052',
    codePath: ['F05', '2'],
    name: 'Environment',
    published: true,
  },
  {
    _key: 'F0519',
    codePath: ['F05', '1', '9'],
    name: 'Biological and related sciences not elsewhere classified',
    published: false,
  },
  {
    _key: 'F059',
    codePath: ['F05', '9'],
    name: 'Natural sciences, mathematics and statistics not elsewhere classified',
    published: false,
  },
  {
    _key: 'F0099',
    codePath: ['F00', '9', '9'],
    name: 'Generic programmes and qualifications not elsewhere classified',
    published: false,
  },
  {
    _key: 'F0788',
    codePath: ['F07', '8', '8'],
    name: 'Inter-disciplinary programmes and qualifications involving engineering, manufacturing and construction',
    published: false,
  },
  {
    _key: 'F049',
    codePath: ['F04', '9'],
    name: 'Business, administration and law not elsewhere classified',
    published: false,
  },
  {
    _key: 'F0230',
    codePath: ['F02', '3', '0'],
    name: 'Languages not further defined',
    published: false,
  },
  {
    _key: 'F0399',
    codePath: ['F03', '9', '9'],
    name: 'Social sciences, journalism and information not elsewhere classified',
    published: false,
  },
  {
    _key: 'F0113',
    codePath: ['F01', '1', '3'],
    name: 'Teacher training without subject specialisation',
    published: true,
  },
  {
    _key: 'F0410',
    codePath: ['F04', '1', '0'],
    name: 'Business and administration not further defined',
    published: false,
  },
  {
    _key: 'F1099',
    codePath: ['F10', '9', '9'],
    name: 'Services not elsewhere classified',
    published: false,
  },
  {
    _key: 'F03',
    codePath: ['F03'],
    name: 'Social sciences, journalism and information',
    published: true,
  },
  {
    _key: 'F0713',
    codePath: ['F07', '1', '3'],
    name: 'Electricity and energy',
    published: true,
  },
  {
    _key: 'F10',
    codePath: ['F10'],
    name: 'Services',
    published: true,
  },
  {
    _key: 'F0319',
    codePath: ['F03', '1', '9'],
    name: 'Social and behavioural sciences not elsewhere classified',
    published: false,
  },
  {
    _key: 'F0232',
    codePath: ['F02', '3', '2'],
    name: 'Literature and linguistics',
    published: true,
  },
  {
    _key: 'F039',
    codePath: ['F03', '9'],
    name: 'Social sciences, journalism and information not elsewhere classified',
    published: false,
  },
  {
    _key: 'F0110',
    codePath: ['F01', '1', '0'],
    name: 'Education not further defined',
    published: false,
  },
  {
    _key: 'F1011',
    codePath: ['F10', '1', '1'],
    name: 'Domestic services',
    published: true,
  },
  {
    _key: 'F051',
    codePath: ['F05', '1'],
    name: 'Biological and related sciences',
    published: true,
  },
  {
    _key: 'F041',
    codePath: ['F04', '1'],
    name: 'Business and administration',
    published: true,
  },
  {
    _key: 'F0500',
    codePath: ['F05', '0', '0'],
    name: 'Natural sciences, mathematics and statistics not further defined',
    published: false,
  },
  {
    _key: 'F0415',
    codePath: ['F04', '1', '5'],
    name: 'Secretarial and office work',
    published: true,
  },
  {
    _key: 'F1041',
    codePath: ['F10', '4', '1'],
    name: 'Transport services',
    published: false,
  },
  {
    _key: 'F0715',
    codePath: ['F07', '1', '5'],
    name: 'Mechanics and metal trades',
    published: true,
  },
  {
    _key: 'F084',
    codePath: ['F08', '4'],
    name: 'Veterinary',
    published: true,
  },
  {
    _key: 'F0712',
    codePath: ['F07', '1', '2'],
    name: 'Environmental protection technology',
    published: true,
  },
  {
    _key: 'F0400',
    codePath: ['F04', '0', '0'],
    name: 'Business, administration and law not further defined',
    published: false,
  },
  {
    _key: 'F1039',
    codePath: ['F10', '3', '9'],
    name: 'Security services not elsewhere classified',
    published: false,
  },
  {
    _key: 'F0412',
    codePath: ['F04', '1', '2'],
    name: 'Finance, banking and insurance',
    published: true,
  },
  {
    _key: 'F0414',
    codePath: ['F04', '1', '4'],
    name: 'Marketing and advertising',
    published: true,
  },
  {
    _key: 'F104',
    codePath: ['F10', '4'],
    name: 'Transport services',
    published: true,
  },
  {
    _key: 'F028',
    codePath: ['F02', '8'],
    name: 'Inter-disciplinary programmes and qualifications involving arts and humanities',
    published: true,
  },
  {
    _key: 'F103',
    codePath: ['F10', '3'],
    name: 'Security services',
    published: true,
  },
  {
    _key: 'F1020',
    codePath: ['F10', '2', '0'],
    name: 'Hygiene and occupational health services not further defined',
    published: true,
  },
  {
    _key: 'F1019',
    codePath: ['F10', '1', '9'],
    name: 'Personal services not elsewhere classified',
    published: false,
  },
  {
    _key: 'F053',
    codePath: ['F05', '3'],
    name: 'Physical sciences',
    published: true,
  },
  {
    _key: 'F081',
    codePath: ['F08', '1'],
    name: 'Agriculture',
    published: true,
  },
  {
    _key: 'F109',
    codePath: ['F10', '9'],
    name: 'Services not elsewhere classified',
    published: false,
  },
  {
    _key: 'F0488',
    codePath: ['F04', '8', '8'],
    name: 'Inter-disciplinary programmes and qualifications involving business, administration and law',
    published: false,
  },
  {
    _key: 'F1031',
    codePath: ['F10', '3', '1'],
    name: 'Military and defence',
    published: true,
  },
  {
    _key: 'F090',
    codePath: ['F09', '0'],
    name: 'Health and welfare not further defined',
    published: false,
  },
  {
    _key: 'F0520',
    codePath: ['F05', '2', '0'],
    name: 'Environment not further defined',
    published: false,
  },
  {
    _key: 'F00',
    codePath: ['F00'],
    name: 'Generic programmes and qualifications',
    published: true,
  },
  {
    _key: 'F032',
    codePath: ['F03', '2'],
    name: 'Journalism and information',
    published: true,
  },
  {
    _key: 'F0329',
    codePath: ['F03', '2', '9'],
    name: 'Journalism and information not elsewhere classified',
    published: false,
  },
  {
    _key: 'F101',
    codePath: ['F10', '1'],
    name: 'Personal services',
    published: true,
  },
  {
    _key: 'F0320',
    codePath: ['F03', '2', '0'],
    name: 'Journalism and information not further defined',
    published: false,
  },
  {
    _key: 'F088',
    codePath: ['F08', '8'],
    name: 'Inter-disciplinary programmes and qualifications involving agriculture, forestry, fisheries and veterinary',
    published: true,
  },
  {
    _key: 'F102',
    codePath: ['F10', '2'],
    name: 'Hygiene and occupational health services',
    published: true,
  },
  {
    _key: 'F0388',
    codePath: ['F03', '8', '8'],
    name: 'Inter-disciplinary programmes and qualifications involving social sciences, journalism and information',
    published: false,
  },
  {
    _key: 'F0312',
    codePath: ['F03', '1', '2'],
    name: 'Political sciences and civics',
    published: true,
  },
  {
    _key: 'F0899',
    codePath: ['F08', '9', '9'],
    name: 'Agriculture, forestry, fisheries and veterinary not elsewhere classified',
    published: false,
  },
  {
    _key: 'F0311',
    codePath: ['F03', '1', '1'],
    name: 'Economics',
    published: true,
  },
  {
    _key: 'F050',
    codePath: ['F05', '0'],
    name: 'Natural sciences, mathematics and statistics not further defined',
    published: false,
  },
  {
    _key: 'F0114',
    codePath: ['F01', '1', '4'],
    name: 'Teacher training with subject specialisation',
    published: true,
  },
  {
    _key: 'F031',
    codePath: ['F03', '1'],
    name: 'Social and behavioural sciences',
    published: true,
  },
  {
    _key: 'F021',
    codePath: ['F02', '1'],
    name: 'Arts',
    published: true,
  },
  {
    _key: 'F0314',
    codePath: ['F03', '1', '4'],
    name: 'Sociology and cultural studies',
    published: true,
  },
  {
    _key: 'F0210',
    codePath: ['F02', '1', '0'],
    name: 'Arts not further defined',
    published: false,
  },
  {
    _key: 'F0916',
    codePath: ['F09', '1', '6'],
    name: 'Pharmacy',
    published: true,
  },
  {
    _key: 'F0313',
    codePath: ['F03', '1', '3'],
    name: 'Psychology',
    published: true,
  },
  {
    _key: 'F038',
    codePath: ['F03', '8'],
    name: 'Inter-disciplinary programmes and qualifications involving social sciences, journalism and information',
    published: true,
  },
  {
    _key: 'F0322',
    codePath: ['F03', '2', '2'],
    name: 'Library, information and archival studies',
    published: true,
  },
  {
    _key: 'F0310',
    codePath: ['F03', '1', '0'],
    name: 'Social and behavioural sciences not further defined',
    published: false,
  },
  {
    _key: 'F1088',
    codePath: ['F10', '8', '8'],
    name: 'Inter-disciplinary programmes and qualifications involving services',
    published: false,
  },
  {
    _key: 'F1029',
    codePath: ['F10', '2', '9'],
    name: 'Hygiene and occupational health services not elsewhere classified',
    published: false,
  },
  {
    _key: 'F0219',
    codePath: ['F02', '1', '9'],
    name: 'Arts not elsewhere classified',
    published: false,
  },
  {
    _key: 'F0229',
    codePath: ['F02', '2', '9'],
    name: 'Humanities (except languages) not elsewhere classified',
    published: false,
  },
  {
    _key: 'F091',
    codePath: ['F09', '1'],
    name: 'Health',
    published: true,
  },
  {
    _key: 'F0511',
    codePath: ['F05', '1', '1'],
    name: 'Biology',
    published: true,
  },
  {
    _key: 'F0542',
    codePath: ['F05', '4', '2'],
    name: 'Statistics',
    published: true,
  },
  {
    _key: 'F0223',
    codePath: ['F02', '2', '3'],
    name: 'Philosophy and ethics',
    published: true,
  },
  {
    _key: 'F0521',
    codePath: ['F05', '2', '1'],
    name: 'Environmental sciences',
    published: true,
  },
  {
    _key: 'F0510',
    codePath: ['F05', '1', '0'],
    name: 'Biological and related sciences not further defined',
    published: false,
  },
  {
    _key: 'F0231',
    codePath: ['F02', '3', '1'],
    name: 'Language acquisition',
    published: true,
  },
  {
    _key: 'F09',
    codePath: ['F09'],
    name: 'Health and welfare',
    published: true,
  },
  {
    _key: 'F04',
    codePath: ['F04'],
    name: 'Business, administration and law',
    published: true,
  },
  {
    _key: 'F092',
    codePath: ['F09', '2'],
    name: 'Welfare',
    published: true,
  },
  {
    _key: 'F0588',
    codePath: ['F05', '8', '8'],
    name: 'Inter-disciplinary programmes and qualifications involving natural sciences, mathematics and statistics',
    published: false,
  },
  {
    _key: 'F05',
    codePath: ['F05'],
    name: 'Natural sciences, mathematics and statistics',
    published: true,
  },
  {
    _key: 'F1021',
    codePath: ['F10', '2', '1'],
    name: 'Community sanitation',
    published: true,
  },
  {
    _key: 'F0288',
    codePath: ['F02', '8', '8'],
    name: 'Inter-disciplinary programmes and qualifications involving arts and humanities',
    published: false,
  },
  {
    _key: 'F1013',
    codePath: ['F10', '1', '3'],
    name: 'Hotel, restaurants and catering',
    published: true,
  },
  {
    _key: 'F070',
    codePath: ['F07', '0'],
    name: 'Engineering, manufacturing and construction not further defined',
    published: false,
  },
  {
    _key: 'F108',
    codePath: ['F10', '8'],
    name: 'Inter-disciplinary programmes and qualifications involving services',
    published: true,
  },
  {
    _key: 'F0299',
    codePath: ['F02', '9', '9'],
    name: 'Arts and humanities not elsewhere classified',
    published: false,
  },
  {
    _key: 'F079',
    codePath: ['F07', '9'],
    name: 'Engineering, manufacturing and construction not elsewhere classified',
    published: false,
  },
  {
    _key: 'F0530',
    codePath: ['F05', '3', '0'],
    name: 'Physical sciences not further defined',
    published: false,
  },
  {
    _key: 'F0914',
    codePath: ['F09', '1', '4'],
    name: 'Medical diagnostic and treatment technology',
    published: true,
  },
  {
    _key: 'F042',
    codePath: ['F04', '2'],
    name: 'Law',
    published: true,
  },
  {
    _key: 'F099',
    codePath: ['F09', '9'],
    name: 'Health and welfare not elsewhere classified',
    published: false,
  },
  {
    _key: 'F02',
    codePath: ['F02'],
    name: 'Arts and humanities',
    published: true,
  },
  {
    _key: 'F0531',
    codePath: ['F05', '3', '1'],
    name: 'Chemistry',
    published: true,
  },
  {
    _key: 'F0215',
    codePath: ['F02', '1', '5'],
    name: 'Music and performing arts',
    published: true,
  },
  {
    _key: 'F0912',
    codePath: ['F09', '1', '2'],
    name: 'Medicine',
    published: true,
  },
  {
    _key: 'F054',
    codePath: ['F05', '4'],
    name: 'Mathematics and statistics',
    published: true,
  },
  {
    _key: 'F0540',
    codePath: ['F05', '4', '0'],
    name: 'Mathematics and statistics not further defined',
    published: false,
  },
  {
    _key: 'F0541',
    codePath: ['F05', '4', '1'],
    name: 'Mathematics',
    published: true,
  },
  {
    _key: 'F003',
    codePath: ['F00', '3'],
    name: 'Personal skills and development',
    published: true,
  },
  {
    _key: 'F058',
    codePath: ['F05', '8'],
    name: 'Inter-disciplinary programmes and qualifications involving natural sciences, mathematics and statistics',
    published: true,
  },
  {
    _key: 'F06',
    codePath: ['F06'],
    name: 'Information and Communication Technologies',
    published: true,
  },
  {
    _key: 'F0921',
    codePath: ['F09', '2', '1'],
    name: 'Care of the elderly and of disabled adults',
    published: true,
  },
  {
    _key: 'F0999',
    codePath: ['F09', '9', '9'],
    name: 'Health and welfare not elsewhere classified',
    published: false,
  },
  {
    _key: 'F068',
    codePath: ['F06', '8'],
    name: 'Inter-disciplinary programmes and qualifications involving information and Communication Technologies',
    published: true,
  },
  {
    _key: 'F0610',
    codePath: ['F06', '1', '0'],
    name: 'Information and Communication Technologies not further defined',
    published: false,
  },
  {
    _key: 'F0000',
    codePath: ['F00', '0', '0'],
    name: 'Generic programmes and qualifications not further defined',
    published: false,
  },
  {
    _key: 'F0724',
    codePath: ['F07', '2', '4'],
    name: 'Mining and extraction',
    published: true,
  },
  {
    _key: 'F0611',
    codePath: ['F06', '1', '1'],
    name: 'Computer use',
    published: true,
  },
  {
    _key: 'F0831',
    codePath: ['F08', '3', '1'],
    name: 'Fisheries',
    published: false,
  },
  {
    _key: 'F1012',
    codePath: ['F10', '1', '2'],
    name: 'Hair and beauty services',
    published: true,
  },
  {
    _key: 'F0612',
    codePath: ['F06', '1', '2'],
    name: 'Database and network design and administration',
    published: true,
  },
  {
    _key: 'F0119',
    codePath: ['F01', '1', '9'],
    name: 'Education not elsewhere classified',
    published: false,
  },
  {
    _key: 'F0613',
    codePath: ['F06', '1', '3'],
    name: 'Software and applications development and analysis',
    published: true,
  },
  {
    _key: 'F0720',
    codePath: ['F07', '2', '0'],
    name: 'Manufacturing and processing not further defined',
    published: false,
  },
  {
    _key: 'F0619',
    codePath: ['F06', '1', '9'],
    name: 'Information and Communication Technologies not elsewhere classified',
    published: false,
  },
  {
    _key: 'F0688',
    codePath: ['F06', '8', '8'],
    name: 'Inter-disciplinary programmes and qualifications involving information and Communication Technologies',
    published: false,
  },
  {
    _key: 'F07',
    codePath: ['F07'],
    name: 'Engineering, manufacturing and construction',
    published: true,
  },
  {
    _key: 'F0722',
    codePath: ['F07', '2', '2'],
    name: 'Materials (glass, paper, plastic and wood)',
    published: true,
  },
  {
    _key: 'F030',
    codePath: ['F03', '0'],
    name: 'Social sciences, journalism and information not further defined',
    published: false,
  },
  {
    _key: 'F0700',
    codePath: ['F07', '0', '0'],
    name: 'Engineering, manufacturing and construction not further defined',
    published: false,
  },
  {
    _key: 'F0710',
    codePath: ['F07', '1', '0'],
    name: 'Engineering and engineering trades not further defined',
    published: false,
  },
  {
    _key: 'F072',
    codePath: ['F07', '2'],
    name: 'Manufacturing and processing',
    published: true,
  },
  {
    _key: 'F001',
    codePath: ['F00', '1'],
    name: 'Basic programmes and qualifications',
    published: true,
  },
  {
    _key: 'F0719',
    codePath: ['F07', '1', '9'],
    name: 'Engineering and engineering trades not elsewhere classified',
    published: false,
  },
  {
    _key: 'F0721',
    codePath: ['F07', '2', '1'],
    name: 'Food processing',
    published: true,
  },
  {
    _key: 'F002',
    codePath: ['F00', '2'],
    name: 'Literacy and numeracy',
    published: true,
  },
  {
    _key: 'F0723',
    codePath: ['F07', '2', '3'],
    name: 'Textiles (clothes, footwear and leather)',
    published: true,
  },
  {
    _key: 'F0729',
    codePath: ['F07', '2', '9'],
    name: 'Manufacturing and processing not elsewhere classified',
    published: false,
  },
  {
    _key: 'F0923',
    codePath: ['F09', '2', '3'],
    name: 'Social work and counselling',
    published: true,
  },
  {
    _key: 'F073',
    codePath: ['F07', '3'],
    name: 'Architecture and construction',
    published: true,
  },
  {
    _key: 'F0730',
    codePath: ['F07', '3', '0'],
    name: 'Architecture and construction not further defined',
    published: false,
  },
  {
    _key: 'F1022',
    codePath: ['F10', '2', '2'],
    name: 'Occupational health and safety',
    published: true,
  },
  {
    _key: 'F0731',
    codePath: ['F07', '3', '1'],
    name: 'Architecture and town planning',
    published: false,
  },
  {
    _key: 'F0732',
    codePath: ['F07', '3', '2'],
    name: 'Building and civil engineering',
    published: true,
  },
  {
    _key: 'F0599',
    codePath: ['F05', '9', '9'],
    name: 'Natural sciences, mathematics and statistics not elsewhere classified',
    published: false,
  },
  {
    _key: 'F078',
    codePath: ['F07', '8'],
    name: 'Inter-disciplinary programmes and qualifications involving engineering, manufacturing and construction',
    published: true,
  },
  {
    _key: 'F0799',
    codePath: ['F07', '9', '9'],
    name: 'Engineering, manufacturing and construction not elsewhere classified',
    published: false,
  },
  {
    _key: 'F080',
    codePath: ['F08', '0'],
    name: 'Agriculture, forestry, fisheries and veterinary not further defined',
    published: false,
  },
  {
    _key: 'F011',
    codePath: ['F01', '1'],
    name: 'Education',
    published: false,
  },
  {
    _key: 'F061',
    codePath: ['F06', '1'],
    name: 'Information and Communication Technologies',
    published: false,
  },
  {
    _key: 'F0800',
    codePath: ['F08', '0', '0'],
    name: 'Agriculture, forestry, fisheries and veterinary not further defined',
    published: false,
  },
  {
    _key: 'F1014',
    codePath: ['F10', '1', '4'],
    name: 'Sports',
    published: true,
  },
  {
    _key: 'F0811',
    codePath: ['F08', '1', '1'],
    name: 'Crop and livestock production',
    published: true,
  },
  {
    _key: 'F048',
    codePath: ['F04', '8'],
    name: 'Inter-disciplinary programmes and qualifications involving business, administration and law',
    published: true,
  },
  {
    _key: 'F0819',
    codePath: ['F08', '1', '9'],
    name: 'Agriculture not elsewhere classified',
    published: false,
  },
  {
    _key: 'F020',
    codePath: ['F02', '0'],
    name: 'Arts and humanities not further defined',
    published: false,
  },
  {
    _key: 'F082',
    codePath: ['F08', '2'],
    name: 'Forestry',
    published: true,
  },
  {
    _key: 'F0411',
    codePath: ['F04', '1', '1'],
    name: 'Accounting and taxation',
    published: true,
  },
  {
    _key: 'F0841',
    codePath: ['F08', '4', '1'],
    name: 'Veterinary',
    published: false,
  },
  {
    _key: 'F0888',
    codePath: ['F08', '8', '8'],
    name: 'Inter-disciplinary programmes and qualifications involving agriculture, forestry, fisheries and veterinary',
    published: false,
  },
  {
    _key: 'F089',
    codePath: ['F08', '9'],
    name: 'Agriculture, forestry, fisheries and veterinary not elsewhere classified',
    published: false,
  },
  {
    _key: 'F0810',
    codePath: ['F08', '1', '0'],
    name: 'Agriculture not further defined',
    published: false,
  },
  {
    _key: 'F0900',
    codePath: ['F09', '0', '0'],
    name: 'Health and welfare not further defined',
    published: false,
  },
  {
    _key: 'F0911',
    codePath: ['F09', '1', '1'],
    name: 'Dental studies',
    published: true,
  },
  {
    _key: 'F0716',
    codePath: ['F07', '1', '6'],
    name: 'Motor vehicles, ships and aircraft',
    published: true,
  },
]
