export default [
  {
    _key: 'ED661',
    codePath: ['6', '6', '1'],
    name: "Bachelor's or equivalent - orientation unspecified, insufficient for level completion",
    published: false,
  },
  {
    _key: 'ED02',
    codePath: ['0', '2'],
    name: 'Pre-primary education',
    published: false,
  },
  {
    _key: 'ED66',
    codePath: ['6', '6'],
    name: "Bachelor's or equivalent - orientation unspecified",
    published: false,
  },
  {
    _key: 'ED351',
    codePath: ['3', '5', '1'],
    name: 'Upper secondary education - vocational, insufficient for level completion or partial level completion, without direct access to tertiary education',
    published: false,
  },
  {
    _key: 'ED65',
    codePath: ['6', '5'],
    name: "Bachelor's or equivalent - professional",
    published: false,
  },
  {
    _key: 'ED646',
    codePath: ['6', '4', '6'],
    name: "Bachelor's or equivalent - academic, long first degree (more than 4 years)",
    published: false,
  },
  {
    _key: 'ED645',
    codePath: ['6', '4', '5'],
    name: "Bachelor's or equivalent - academic, first degree (3-4 years)",
    published: false,
  },
  {
    _key: 'ED657',
    codePath: ['6', '5', '7'],
    name: "Bachelor's or equivalent - professional, second or further degree (following a Bachelor's or equivalent programme)",
    published: false,
  },
  {
    _key: 'ED551',
    codePath: ['5', '5', '1'],
    name: 'Tertiary education - vocational/professional, insufficient for level completion',
    published: false,
  },
  {
    _key: 'ED641',
    codePath: ['6', '4', '1'],
    name: "Bachelor's or equivalent - academic, insufficient for level completion",
    published: false,
  },
  {
    _key: 'ED352',
    codePath: ['3', '5', '2'],
    name: 'Upper secondary education - vocational, sufficient for partial level completion, without direct access to tertiary education',
    published: false,
  },
  {
    _key: 'ED6',
    codePath: ['6'],
    name: 'Bachelor’s or equivalent',
    published: true,
  },
  {
    _key: 'ED353',
    codePath: ['3', '5', '3'],
    name: 'Upper secondary education - vocational, sufficient for level completion, without direct access to tertiary education',
    published: false,
  },
  {
    _key: 'ED758',
    codePath: ['7', '5', '8'],
    name: "Master's or equivalent - professional, second or further degree (following a Master's or equivalent programme)",
    published: false,
  },
  {
    _key: 'ED554',
    codePath: ['5', '5', '4'],
    name: 'Tertiary education - vocational/professional, sufficient for level completion',
    published: false,
  },
  {
    _key: 'ED2',
    codePath: ['2'],
    name: 'Lower secondary education',
    published: true,
  },
  {
    _key: 'ED55',
    codePath: ['5', '5'],
    name: 'Tertiary education - vocational/professional',
    published: false,
  },
  {
    _key: 'ED541',
    codePath: ['5', '4', '1'],
    name: 'Tertiary education - general/academic, insufficient for level completion',
    published: false,
  },
  {
    _key: 'ED45',
    codePath: ['4', '5'],
    name: 'Post-secondary non-tertiary education - vocational',
    published: false,
  },
  {
    _key: 'ED454',
    codePath: ['4', '5', '4'],
    name: 'Post-secondary non-tertiary education - vocational, sufficient for level completion, with direct access to tertiary education',
    published: false,
  },
  {
    _key: 'ED453',
    codePath: ['4', '5', '3'],
    name: 'Post-secondary non-tertiary education - vocational, sufficient for level completion, without direct access to tertiary education',
    published: false,
  },
  {
    _key: 'ED4',
    codePath: ['4'],
    name: 'Post-secondary non-tertiary education',
    published: true,
  },
  {
    _key: 'ED01',
    codePath: ['0', '1'],
    name: 'Early childhood educational development',
    published: false,
  },
  {
    _key: 'ED741',
    codePath: ['7', '4', '1'],
    name: "Master's or equivalent - academic, insufficient for level completion",
    published: false,
  },
  {
    _key: 'ED667',
    codePath: ['6', '6', '7'],
    name: "Bachelor's or equivalent - orientation unspecified, second or further degree (following a Bachelor's or equivalent programme)",
    published: false,
  },
  {
    _key: 'ED544',
    codePath: ['5', '4', '4'],
    name: 'Tertiary education - general/academic, sufficient for level completion',
    published: false,
  },
  {
    _key: 'ED25',
    codePath: ['2', '5'],
    name: 'Lower secondary education - vocational',
    published: false,
  },
  {
    _key: 'ED76',
    codePath: ['7', '6'],
    name: "Master's or equivalent - orientation unspecified",
    published: false,
  },
  {
    _key: 'ED441',
    codePath: ['4', '4', '1'],
    name: 'Post-secondary non-tertiary education - general, insufficient for level completion, without direct access to tertiary education',
    published: false,
  },
  {
    _key: 'ED444',
    codePath: ['4', '4', '4'],
    name: 'Post-secondary non-tertiary education - general, sufficient for level completion, with direct access to tertiary education',
    published: false,
  },
  {
    _key: 'ED655',
    codePath: ['6', '5', '5'],
    name: "Bachelor's or equivalent - professional, first degree (3-4 years)",
    published: false,
  },
  {
    _key: 'ED8',
    codePath: ['8'],
    name: 'Doctoral or equivalent',
    published: true,
  },
  {
    _key: 'ED44',
    codePath: ['4', '4'],
    name: 'Post-secondary non-tertiary education - general',
    published: false,
  },
  {
    _key: 'ADT',
    codePath: ['ADT'],
    name: 'Adult Education',
    published: true,
  },
  {
    _key: 'ED75',
    codePath: ['7', '5'],
    name: "Master's or equivalent - professional",
    published: false,
  },
  {
    _key: 'ED3',
    codePath: ['3'],
    name: 'Upper secondary education',
    published: true,
  },
  {
    _key: 'ED666',
    codePath: ['6', '6', '6'],
    name: "Bachelor's or equivalent - orientation unspecified, long first degree (more than 4 years)",
    published: false,
  },
  {
    _key: 'ED757',
    codePath: ['7', '5', '7'],
    name: "Master's or equivalent - professional, second or further degree (following a Bachelor's or equivalent programme)",
    published: false,
  },
  {
    _key: 'ED746',
    codePath: ['7', '4', '6'],
    name: "Master's or equivalent - academic, long first degree (at least 5 years)",
    published: false,
  },
  {
    _key: 'ED751',
    codePath: ['7', '5', '1'],
    name: "Master's or equivalent - professional, insufficient for level completion",
    published: false,
  },
  {
    _key: 'ED756',
    codePath: ['7', '5', '6'],
    name: "Master's or equivalent - professional, long first degree (at least 5 years)",
    published: false,
  },
  {
    _key: 'ED766',
    codePath: ['7', '6', '6'],
    name: "Master's or equivalent - orientation unspecified, long first degree (at least 5 years)",
    published: false,
  },
  {
    _key: 'ED443',
    codePath: ['4', '4', '3'],
    name: 'Post-secondary non-tertiary education - general, sufficient for level completion, without direct access to tertiary education',
    published: false,
  },
  {
    _key: 'ED767',
    codePath: ['7', '6', '7'],
    name: "Master's or equivalent - orientation unspecified, second or further degree (following a Bachelor's or equivalent programme)",
    published: false,
  },
  {
    _key: 'ED768',
    codePath: ['7', '6', '8'],
    name: "Master's or equivalent - orientation unspecified, second or further degree (following a Master's or equivalent programme)",
    published: false,
  },
  {
    _key: 'ED747',
    codePath: ['7', '4', '7'],
    name: "Master's or equivalent - academic, second or further degree (following a Bachelor's or equivalent programme)",
    published: false,
  },
  {
    _key: 'ED35',
    codePath: ['3', '5'],
    name: 'Upper secondary education - vocational',
    published: false,
  },
  {
    _key: 'ED344',
    codePath: ['3', '4', '4'],
    name: 'Upper secondary education - general, sufficient for level completion, with direct access to tertiary education',
    published: false,
  },
  {
    _key: 'ED24',
    codePath: ['2', '4'],
    name: 'Lower secondary education - general',
    published: false,
  },
  {
    _key: 'ED5',
    codePath: ['5'],
    name: 'Tertiary education',
    published: true,
  },
  {
    _key: 'ED748',
    codePath: ['7', '4', '8'],
    name: "Master's or equivalent - academic, second or further degree (following a Master's or equivalent programme)",
    published: false,
  },
  {
    _key: 'ED343',
    codePath: ['3', '4', '3'],
    name: 'Upper secondary education - general, sufficient for level completion, without direct access to tertiary education',
    published: false,
  },
  {
    _key: 'ED656',
    codePath: ['6', '5', '6'],
    name: "Bachelor's or equivalent - professional, long first degree (more than 4 years)",
    published: false,
  },
  {
    _key: 'ED0',
    codePath: ['0'],
    name: 'Early childhood education',
    published: true,
  },
  {
    _key: 'ED665',
    codePath: ['6', '6', '5'],
    name: "Bachelor's or equivalent - orientation unspecified, first degree (3-4 years)",
    published: false,
  },
  {
    _key: 'ED354',
    codePath: ['3', '5', '4'],
    name: 'Upper secondary education - vocational, sufficient for level completion, with direct access to tertiary education',
    published: false,
  },
  {
    _key: 'ED451',
    codePath: ['4', '5', '1'],
    name: 'Post-secondary non-tertiary education - vocational, insufficient for level completion, without direct access to tertiary education',
    published: false,
  },
  {
    _key: 'ED34',
    codePath: ['3', '4'],
    name: 'Upper secondary education - general',
    published: false,
  },
  {
    _key: 'ED64',
    codePath: ['6', '4'],
    name: "Bachelor's or equivalent - academic",
    published: false,
  },
  {
    _key: 'ED761',
    codePath: ['7', '6', '1'],
    name: "Master's or equivalent - orientation unspecified, insufficient for level completion",
    published: false,
  },
  {
    _key: 'ED7',
    codePath: ['7'],
    name: 'Master’s or equivalent',
    published: true,
  },
  {
    _key: 'ED341',
    codePath: ['3', '4', '1'],
    name: 'Upper secondary education - general, insufficient for level completion or partial level completion, without direct access to tertiary education',
    published: false,
  },
  {
    _key: 'ED651',
    codePath: ['6', '5', '1'],
    name: "Bachelor's or equivalent - professional, insufficient for level completion",
    published: false,
  },
  {
    _key: 'ED74',
    codePath: ['7', '4'],
    name: "Master's or equivalent - academic",
    published: false,
  },
  {
    _key: 'ED647',
    codePath: ['6', '4', '7'],
    name: "Bachelor's or equivalent - academic, second or further degree (following a Bachelor's or equivalent programme)",
    published: false,
  },
  {
    _key: 'ED1',
    codePath: ['1'],
    name: 'Primary education',
    published: true,
  },
  {
    _key: 'ED54',
    codePath: ['5', '4'],
    name: 'Tertiary education - general/academic',
    published: false,
  },
  {
    _key: 'ED342',
    codePath: ['3', '4', '2'],
    name: 'Upper secondary education - general, sufficient for partial level completion, without direct access to tertiary education',
    published: false,
  },
]
