import type { LearningOutcome, LearningOutcomeOption } from '@moodlenet/ed-meta/common'

export const learningOutcomesSelection: LearningOutcome[] = [
  // {
  //   category: '1',
  //   verb: 'Define',
  //   sentence: 'the concept of ecological balance within ecosystems.',
  // },
  {
    code: '2',
    verb: 'Explain',
    sentence: 'the consequences of habitat fragmentation on biodiversity.',
  },
  {
    code: '3',
    verb: 'Apply',
    sentence: 'conservation principles to protect specific habitats.',
  },
  // {
  //   category: '4',
  //   verb: 'Analyze',
  //   sentence: ' species data to identify ecosystem decline patterns.',
  // },
  {
    code: '5',
    verb: 'Develop',
    sentence: 'a comprehensive plan for ecosystem restoration.',
  },
  // {
  //   category: 'Evaluation',
  //   verb: 'Assess',
  //   sentence: ' the impact and success of conservation projects on biodiversity.',
  // },
]

export const learningOutcomeOptions: LearningOutcomeOption[] = [
  {
    code: '1',
    name: 'Knowledge',
    verbs: [
      'Define',
      'Describe',
      'Identify',
      'Label',
      'List',
      'Match',
      'Memorize',
      'Name',
      'Outline',
      'Recall',
      'Recognize',
      'Relate',
      'Reproduce',
      'Select',
      'State',
    ],
  },
  {
    code: '2',
    name: 'Comprehension',
    verbs: [
      'Classify',
      'Convert',
      'Defend',
      'Discuss',
      'Distinguish',
      'Estimate',
      'Explain',
      'Express',
      'Extend',
      'Generalize',
      'Give examples',
      'Identify',
      'Indicate',
      'Infer',
      'Interpret',
      'Paraphrase',
      'Predict',
      'Rewrite',
      'Report',
      'Restate',
      'Review',
      'Rewrite',
      'Summarize',
      'Translate',
      'Understand',
    ],
  },
  {
    code: '3',
    name: 'Application',
    verbs: [
      'Apply',
      'Change',
      'Choose',
      'Compute',
      'Construct',
      'Develop',
      'Discover',
      'Dramatize',
      'Employ',
      'Illustrate',

      'Interpret',
      'Manipulate',
      'Modify',
      'Operate',
      'Practice',
      'Predict',
      'Prepare',
      'Produce',
      'Relate',
      'Schedule',
      'Show',
      'Sketch',
      'Solve',
      'Use',
      'Write',
    ],
  },

  {
    code: '4',
    name: 'Analysis',
    verbs: [
      'Analyze',
      'Appraise',
      'Break down',
      'Calculate',
      'Categorize',
      'Compare',
      'Contrast',
      'Criticize',
      'Debate',
      'Diagram',
      'Differentiate',
      'Discriminate',
      'Distinguish',
      'Examine',
      'Experiment',
      'Identify',
      'Illustrate',
      'Infer',
      'Inquire',
      'Inspect',
      'Investigate',
      'Outline',
      'Point out',
      'Question',
      'Relate',
      'Research',

      'Select',
      'Separate',
      'Subdivide',
      'Test',
    ],
  },
  {
    code: '5',
    name: 'Synthesis',
    verbs: [
      'Arrange',
      'Assemble',
      'Collect',
      'Compose',
      'Construct',
      'Create',
      'Design',
      'Develop',
      'Devise',
      'Explain',

      'Formulate',
      'Generate',
      'Integrate',
      'Invent',
      'Manage',

      'Organize',
      'Plan',
      'Prepare',
      'Propose',
      'Rearrange',
      'Reconstruct',
      'Relate',
      'Reorganize',
      'Revise',
      'Rewrite',
      'Set up',
      'Summarize',
      'Tell',
      'Write',
    ],
  },
  {
    code: '6',
    name: 'Evaluation',
    verbs: [
      'Appraise',
      'Argue',
      'Assess',
      'Choose',

      'Compare',
      'Conclude',
      'Contrast',
      'Criticize',
      'Critique',
      'Debate',
      'Decide',
      'Defend',
      'Determine',
      'Evaluate',
      'Estimate',
      'Explain',
      'Interpret',
      'Judge',
      'Justify',
      'Measure',
      'Predict',

      'Prioritize',
      'Prove',

      'Rank',
      'Rate',
      'Recommend',
      'Relate',
      'Revise',
      'Score',
      'Select',
      'Summarize',
      'Support',

      'Validate',
      'Value',
    ],
  },
]
