await import('./init/persistence-upgrade.mjs')
await import('./init/kvStore.mjs')
await import('./init/arangodb.mjs')
await import('./init/http-server.mjs')
await import('./init/react-app.mjs')
await import('./init/web-user-events.mjs')
await import('./expose.mjs')
