import { eduBloomCognitiveRecord } from '..'

export const bloomCognitives: eduBloomCognitiveRecord[] = [
  {
    id: '1',
    description: 'Knowledge',
    verbs: [
      'Define',
      'Describe',
      'Identify',
      'Label',
      'List',
      'Match',
      'Description',
      'Outline',
      'Recall',
      'Recognize',
      'Relate',
      'Reproduce',
      'Select',
      'State',
    ],
  },
  {
    id: '2',
    description: 'Comprehension',
    verbs: [
      'Classify',
      'Convert',
      'Defend',
      'Describe',
      'Discuss',
      'Distinguish',
      'Estimate',
      'Explain',
      'Express',
      'Extend',
      'Generalize',
      'Give examples',
      'Identify',
      'Indicate',
      'Infer',
      'Interpret',
      'Paraphrase',
      'Predict',
      'Rewrite',
      'Summarize',
      'Translate',
      'Visualize',
    ],
  },
  {
    id: '3',
    description: 'Application',
    verbs: [
      'Apply',
      'Change',
      'Choose',
      'Compute',
      'Construct',
      'Develop',
      'Discover',
      'Dramatize',
      'Employ',
      'Illustrate',
      'Interpret',
      'Manipulate',
      'Modify',
      'Operate',
      'Practice',
      'Predict',
      'Prepare',
      'Produce',
      'Relate',
      'Schedule',
      'Show',
      'Sketch',
      'Solve',
      'Use',
    ],
  },
  {
    id: '4',
    description: 'Analysis',
    verbs: [
      'Analyze',
      'Appraise',
      'Break down',
      'Calculate',
      'Categorize',
      'Compare',
      'Contrast',
      'Criticize',
      'Diagram',
      'Differentiate',
      'Discriminate',
      'Distinguish',
      'Examine',
      'Experiment',
      'Identify',
      'Illustrate',
      'Infer',
      'Inquire',
      'Inspect',
      'Inventory',
      'Investigate',
      'Outline',
      'Question',
      'Relate',
      'Select',
      'Separate',
      'Subdivide',
    ],
  },
  {
    id: '5',
    description: 'Synthesis',
    verbs: [
      'Arrange',
      'Assemble',
      'Categorize',
      'Collect',
      'Combine',
      'Comply',
      'Compose',
      'Construct',
      'Create',
      'Design',
      'Develop',
      'Devise',
      'Explain',
      'Formulate',
      'Generate',
      'Integrate',
      'Manage',
      'Modify',
      'Organize',
      'Plan',
      'Prepare',
      'Propose',
      'Rearrange',
      'Reconstruct',
      'Relate',
      'Reorganize',
      'Revise',
      'Rewrite',
      'Set up',
      'Summarize',
      'Tell',
      'Write',
    ],
  },
  {
    id: '6',
    description: 'Evaluation',
    verbs: [
      'Appraise',
      'Argue',
      'Assess',
      'Choose',
      'Compare',
      'Conclude',
      'Contrast',
      'Criticize',
      'Critique',
      'Debate',
      'Decide',
      'Deduce',
      'Defend',
      'Determine',
      'Disprove',
      'Estimate',
      'Evaluate',
      'Explain',
      'Interpret',
      'Judge',
      'Justify',
      'Measure',
      'Predict',
      'Prioritize',
      'Prove',
      'Rank',
      'Rate',
      'Recommend',
      'Relate',
      'Revise',
      'Score',
      'Select',
      'Summarize',
      'Support',
      'Value',
    ],
  },
]
