import { License } from '../types/node'
import { localOrg_authId } from './content'

// @ts-ignore: this is a static initial population array, no need to ts check
const _: License[] = [
  {
    _permId: 'cc-0',
    _type: 'License',
    _slug: 'cc-0-public-domain',
    _published: true,
    name: 'Public domain',
    code: 'cc-0',
    description: 'Public domain',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'cc-by',
    _type: 'License',
    _slug: 'cc-by-attribution',
    _published: true,
    name: 'Attribution',
    code: 'cc-by',
    description: 'Attribution',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'cc-by-sa',
    _type: 'License',
    _slug: 'cc-by-sa-attribution-sharealike',
    _published: true,
    name: 'Attribution + ShareAlike',
    code: 'cc-by-sa',
    description: 'Attribution + ShareAlike',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'cc-by-nc',
    _type: 'License',
    _slug: 'cc-by-nc-attribution-noncommercial',
    _published: true,
    name: 'Attribution + NonCommercial',
    code: 'cc-by-nc',
    description: 'Attribution + NonCommercial',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'cc-by-nc-sa',
    _type: 'License',
    _slug: 'cc-by-nc-sa-attribution-noncommercial-sharealike',
    _published: true,
    name: 'Attribution + NonCommercial + ShareAlike',
    code: 'cc-by-nc-sa',
    description: 'Attribution + NonCommercial + ShareAlike',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'cc-by-nd',
    _type: 'License',
    _slug: 'cc-by-nd-attribution-noderivatives',
    _published: true,
    name: 'Attribution NoDerivatives',
    code: 'cc-by-nd',
    description: 'Attribution NoDerivatives',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'cc-by-nc-nd',
    _type: 'License',
    _slug: 'cc-by-nc-nd-attribution-noncommercial-noderivatives',
    _published: true,
    name: 'Attribution + NonCommercial + NoDerivatives',
    code: 'cc-by-nc-nd',
    description: 'Attribution + NonCommercial + NoDerivatives',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'other-open',
    _type: 'License',
    _slug: 'other-open-other-open-license',
    _published: false,
    name: 'Other open license',
    code: 'other-open',
    description: 'Other open license',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'restricted-copyright',
    _type: 'License',
    _slug: 'restricted-copyright-restricted-copyrighted',
    _published: false,
    name: 'Restricted / copyrighted',
    code: 'restricted-copyright',
    description: 'Restricted / copyrighted',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
]
export default _
