import { ResourceType } from '../types/node'
import { localOrg_authId } from './content'

// @ts-ignore: this is a static initial population array, no need to ts check
const _: ResourceType[] = [
  {
    _permId: 'assessment',
    _type: 'ResourceType',
    _slug: 'assessment',
    _published: true,
    code: 'assessment',
    name: 'Assessment',
    description: 'Assessment',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'concept-map',
    _type: 'ResourceType',
    _slug: 'concept-map',
    _published: true,
    code: 'concept-map',
    name: 'Concept map',
    description: 'Concept map',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'course',
    _type: 'ResourceType',
    _slug: 'course',
    _published: true,
    code: 'course',
    name: 'Course',
    description: 'Course',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'curriculum',
    _type: 'ResourceType',
    _slug: 'curriculum',
    _published: true,
    code: 'curriculum',
    name: 'Curriculum',
    description: 'Curriculum',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'data-set',
    _type: 'ResourceType',
    _slug: 'data-set',
    _published: true,
    code: 'data-set',
    name: 'Data set',
    description: 'Data set',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'experiment',
    _type: 'ResourceType',
    _slug: 'experiment',
    _published: true,
    code: 'experiment',
    name: 'Experiment',
    description: 'Experiment',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'game',
    _type: 'ResourceType',
    _slug: 'game',
    _published: true,
    code: 'game',
    name: 'Game',
    description: 'Game',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'glossary',
    _type: 'ResourceType',
    _slug: 'glossary',
    _published: true,
    code: 'glossary',
    name: 'Glossary',
    description: 'Glossary',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'graph',
    _type: 'ResourceType',
    _slug: 'graph',
    _published: true,
    code: 'graph',
    name: 'Graph',
    description: 'Graph',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'guides-and-tutorials',
    _type: 'ResourceType',
    _slug: 'guides-and-tutorials',
    _published: true,
    code: 'guides-and-tutorials',
    name: 'Guides and Tutorials',
    description: 'Guides and Tutorials',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'interactive-learning-object',
    _type: 'ResourceType',
    _slug: 'interactive-learning-object',
    _published: true,
    code: 'interactive-learning-object',
    name: 'Interactive learning object',
    description: 'Interactive learning object',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'map',
    _type: 'ResourceType',
    _slug: 'map',
    _published: true,
    code: 'map',
    name: 'Map',
    description: 'Map',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'online-courses-site',
    _type: 'ResourceType',
    _slug: 'online-courses-site',
    _published: true,
    code: 'online-courses-site',
    name: 'Online courses site',
    description: 'Online courses site',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'project',
    _type: 'ResourceType',
    _slug: 'project',
    _published: true,
    code: 'project',
    name: 'Project',
    description: 'Project',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'questionnaire',
    _type: 'ResourceType',
    _slug: 'questionnaire',
    _published: true,
    code: 'questionnaire',
    name: 'Questionnaire',
    description: 'Questionnaire',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'reading',
    _type: 'ResourceType',
    _slug: 'reading',
    _published: true,
    code: 'reading',
    name: 'Reading',
    description: 'Reading',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'references',
    _type: 'ResourceType',
    _slug: 'references',
    _published: true,
    code: 'references',
    name: 'References',
    description: 'References',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'report',
    _type: 'ResourceType',
    _slug: 'report',
    _published: true,
    code: 'report',
    name: 'Report',
    description: 'Report',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'repository',
    _type: 'ResourceType',
    _slug: 'repository',
    _published: true,
    code: 'repository',
    name: 'Repository',
    description: 'Repository',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'simulation',
    _type: 'ResourceType',
    _slug: 'simulation',
    _published: true,
    code: 'simulation',
    name: 'Simulation',
    description: 'Simulation',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
  {
    _permId: 'unit-of-study',
    _type: 'ResourceType',
    _slug: 'unit-of-study',
    _published: true,
    code: 'unit-of-study',
    name: 'Unit of study',
    description: 'Unit of study',
    _created: 1636588800000,
    _edited: 1636588800000,
    _authKey: null,
    _creator: localOrg_authId,
    _local: true,
  },
]
export default _
