const fs = require('fs')
files().forEach(f => {
  const content = fs.readFileSync(f, 'utf8')
  fs.writeFileSync(
    f,
    `"use client"
${content}`,
    'utf8',
  )
})

function files() {
  return [
    './email-templates/EmailLayout.tsx',
    './molecules/ImageContainer/ImageContainer.stories.tsx',
    './molecules/ImageContainer/ImageContainer.tsx',
    './molecules/modals/ReportModal/ReportModal.tsx',
    './molecules/embeds/Vimeo/Vimeo.tsx',
    './molecules/embeds/Youtube/Youtube.tsx',
    './molecules/cards/AddToCollectionsCard/AddToCollectionsCard.stories.props.tsx',
    './molecules/cards/AddToCollectionsCard/AddToCollectionsCard.tsx',
    './molecules/cards/ListCard/ListCard.tsx',
    './organisms/SearchImage/SearchImage.tsx',
    './organisms/SearchImage/SearchImage.stories.tsx',
    './organisms/Header/Standard/Header.stories.props.tsx',
    './organisms/Header/Minimalistic/MinimalisticHeader.tsx',
    './atoms/TertiaryButton/TertiaryButton.tsx',
    './atoms/TertiaryButton/TertiaryButton.stories.tsx',
    './atoms/Colorpicker/Colorpicker.tsx',
    './atoms/Colorpicker/Colorpicker.stories.tsx',
    './atoms/Searchbox/Searchbox.tsx',
    './atoms/Dropdown/Dropdown.tsx',
    './atoms/Dropdown/utils.tsx',
    './atoms/Dropdown/DropdownFieldsMockData.tsx',
    './atoms/Dropdown/MultipeSelectDropdown/MultipeSelectDropdown.tsx',
    './atoms/Dropdown/stories/DropdownProps.stories.props.tsx',
    './atoms/Dropdown/stories/Dropdown.stories.tsx',
    './atoms/VisibilityDropdown/VisibilityDropdown.tsx',
    './atoms/Snackbar/SnackbarStack.tsx',
    './atoms/Snackbar/Snackbar.tsx',
    './atoms/Snackbar/Snackbar.stories.tsx',
    './atoms/Snackbar/SnackbarContext.tsx',
    './atoms/PrimaryButton/PrimaryButton.tsx',
    './atoms/PrimaryButton/PrimaryButton.stories.tsx',
    './atoms/FileUploader/FileUploader.tsx',
    './atoms/FileUploader/FileUploader.stories.tsx',
    './atoms/InputTextField/InputTextField.stories.tsx',
    './atoms/InputTextField/InputTextField.tsx',
    './atoms/RoundButton/RoundButton.tsx',
    './atoms/RoundButton/RoundButton.stories.tsx',
    './atoms/SimpleDropdown/SimpleDropdown.tsx',
    './atoms/SimpleDropdown/SimpleDropdown.stories.tsx',
    './atoms/Modal/Modal.stories.tsx',
    './atoms/Modal/Modal.tsx',
    './atoms/Card/Card.stories.tsx',
    './atoms/Card/Card.tsx',
    './atoms/ErrorMessage/ErrorMessage.tsx',
    './atoms/Loading/Loading.tsx',
    './atoms/Loading/Loading.stories.tsx',
    './atoms/SecondaryButton/SecondaryButton.tsx',
    './atoms/SecondaryButton/SecondaryButton.stories.tsx',
    './atoms/Switch/Switch.tsx',
    './atoms/Switch/Switch.stories.tsx',
    './atoms/FloatingMenu/FloatingMenu.tsx',
    './atoms/FloatingMenu/FloatingMenu.stories.tsx',
  ]
}
