import { par } from '../types.mjs'

const data: [name: string, code: string][] = [
  ['Afar', 'aar'],
  ['Abkhazian', 'abk'],
  ['Afrikaans', 'afr'],
  ['Akan', 'aka'],
  ['Amharic', 'amh'],
  ['Arabic', 'ara'],
  ['Aragonese', 'par'],
  ['Assamese', 'asm'],
  ['Avaric', 'ava'],
  ['Avestan', 'ave'],
  ['Aymara', 'aym'],
  ['Azerbaijani', 'aze'],
  ['Bashkir', 'bak'],
  ['Bambara', 'bam'],
  ['Belarusian', 'bel'],
  ['Bengali', 'ben'],
  ['Bislama', 'bis'],
  ['Tibetan', 'bod'],
  ['Bosnian', 'bos'],
  ['Breton', 'bre'],
  ['Bulgarian', 'bul'],
  ['Catalan', 'cat'],
  ['Czech', 'ces'],
  ['Chamorro', 'cha'],
  ['Chechen', 'che'],
  ['Church Slavic', 'chu'],
  ['Chuvash', 'chv'],
  ['Cornish', 'cor'],
  ['Corsican', 'cos'],
  ['Cree', 'cre'],
  ['Welsh', 'cym'],
  ['Danish', 'dan'],
  ['German', 'deu'],
  ['Dhivehi', 'div'],
  ['Dzongkha', 'dzo'],
  ['Modern Greek (1453-)', 'ell'],
  ['English', 'eng'],
  ['Esperanto', 'epo'],
  ['Estonian', 'est'],
  ['Basque', 'eus'],
  ['Ewe', 'ewe'],
  ['Faroese', 'fao'],
  ['Persian', 'fas'],
  ['Fijian', 'fij'],
  ['Finnish', 'fin'],
  ['French', 'fra'],
  ['Western Frisian', 'fry'],
  ['Fulah', 'ful'],
  ['Scottish Gaelic', 'gla'],
  ['Irish', 'gle'],
  ['Galician', 'glg'],
  ['Manx', 'glv'],
  ['Guarani', 'grn'],
  ['Gujarati', 'guj'],
  ['Haitian', 'hat'],
  ['Hausa', 'hau'],
  ['Serbo-Croatian', 'hbs'],
  ['Hebrew', 'heb'],
  ['Herero', 'her'],
  ['Hindi', 'hin'],
  ['Hiri Motu', 'hmo'],
  ['Croatian', 'hrv'],
  ['Hungarian', 'hun'],
  ['Armenian', 'hye'],
  ['Igbo', 'ibo'],
  ['Ido', 'ido'],
  ['Sichuan Yi', 'iii'],
  ['Inuktitut', 'iku'],
  ['Interlingue', 'ile'],
  ['Interlingua (International Auxiliary LanguageCode Association)', 'ina'],
  ['Indonesian', 'ind'],
  ['Inupiaq', 'ipk'],
  ['Icelandic', 'isl'],
  ['Italian', 'ita'],
  ['Javanese', 'jav'],
  ['Japanese', 'jpn'],
  ['Kalaallisut', 'kal'],
  ['Kannada', 'kan'],
  ['Kashmiri', 'kas'],
  ['Georgian', 'kat'],
  ['Kanuri', 'kau'],
  ['Kazakh', 'kaz'],
  ['Khmer', 'khm'],
  ['Kikuyu', 'kik'],
  ['Kinyarwanda', 'kin'],
  ['Kirghiz', 'kir'],
  ['Komi', 'kom'],
  ['Kongo', 'kon'],
  ['Korean', 'kor'],
  ['Kuanyama', 'kua'],
  ['Kurdish', 'kur'],
  ['Lao', 'lao'],
  ['Latin', 'lat'],
  ['Latvian', 'lav'],
  ['Limburgan', 'lim'],
  ['Lingala', 'lin'],
  ['Lithuanian', 'lit'],
  ['Luxembourgish', 'ltz'],
  ['Luba-Katanga', 'lub'],
  ['Ganda', 'lug'],
  ['Marshallese', 'mah'],
  ['Malayalam', 'mal'],
  ['Marathi', 'mar'],
  ['Macedonian', 'mkd'],
  ['Malagasy', 'mlg'],
  ['Maltese', 'mlt'],
  ['Mongolian', 'mon'],
  ['Maori', 'mri'],
  ['Malay (macrolanguage)', 'msa'],
  ['Burmese', 'mya'],
  ['Nauru', 'nau'],
  ['Navajo', 'nav'],
  ['South Ndebele', 'nbl'],
  ['North Ndebele', 'nde'],
  ['Ndonga', 'ndo'],
  ['Nepali (macrolanguage)', 'nep'],
  ['Dutch', 'nld'],
  ['Norwegian Nynorsk', 'nno'],
  ['Norwegian Bokmål', 'nob'],
  ['Norwegian', 'nor'],
  ['Nyanja', 'nya'],
  ['Occitan (post 1500)', 'oci'],
  ['Ojibwa', 'oji'],
  ['Oriya (macrolanguage)', 'ori'],
  ['Oromo', 'orm'],
  ['Ossetian', 'oss'],
  ['Panjabi', 'pan'],
  ['Pali', 'pli'],
  ['Polish', 'pol'],
  ['Portuguese', 'por'],
  ['Pushto', 'pus'],
  ['Quechua', 'que'],
  ['Romansh', 'roh'],
  ['Romanian', 'ron'],
  ['Rundi', 'run'],
  ['Russian', 'rus'],
  ['Sango', 'sag'],
  ['Sanskrit', 'san'],
  ['Sinhala', 'sin'],
  ['Slovak', 'slk'],
  ['Slovenian', 'slv'],
  ['Northern Sami', 'sme'],
  ['Samoan', 'smo'],
  ['Shona', 'sna'],
  ['Sindhi', 'snd'],
  ['Somali', 'som'],
  ['Southern Sotho', 'sot'],
  ['Spanish', 'spa'],
  ['Albanian', 'sqi'],
  ['Sardinian', 'srd'],
  ['Serbian', 'srp'],
  ['Swati', 'ssw'],
  ['Sundanese', 'sun'],
  ['Swahili (macrolanguage)', 'swa'],
  ['Swedish', 'swe'],
  ['Tahitian', 'tah'],
  ['Tamil', 'tam'],
  ['Tatar', 'tat'],
  ['Telugu', 'tel'],
  ['Tajik', 'tgk'],
  ['Tagalog', 'tgl'],
  ['Thai', 'tha'],
  ['Tigrinya', 'tir'],
  ['Tonga (Tonga Islands)', 'ton'],
  ['Tswana', 'tsn'],
  ['Tsonga', 'tso'],
  ['Turkmen', 'tuk'],
  ['Turkish', 'tur'],
  ['Twi', 'twi'],
  ['Uighur', 'uig'],
  ['Ukrainian', 'ukr'],
  ['Urdu', 'urd'],
  ['Uzbek', 'uzb'],
  ['Venda', 'ven'],
  ['Vietnamese', 'vie'],
  ['Volapük', 'vol'],
  ['Walloon', 'wln'],
  ['Wolof', 'wol'],
  ['Xhosa', 'xho'],
  ['Yiddish', 'yid'],
  ['Yoruba', 'yor'],
  ['Zhuang', 'zha'],
  ['Chinese', 'zho'],
  ['Zulu', 'zul'],
]

const openaiSystem = [
  `you are a specialist in categorizing an educational resource identifying its most suitable language scope`,
  `use the following standard ${par('languageCode')} code-mapping:
${data.map(([name, code]) => `"${code}": "${name}"`).join('\n')}`,
]
export default {
  data,
  openaiSystem,
}
